process.env.NODE_ENV = "test";
process.env.DATABASE_URL = process.env.TEST_DATABASE_URL ?? "postgresql://borkin_dev@127.0.0.1:55432/borkin_turnos_test?schema=public";
process.env.FRONTEND_URL = "http://localhost:5173";
process.env.JWT_SECRET = "test-access-secret-at-least-32-characters-long";
process.env.JWT_REFRESH_SECRET = "test-refresh-secret-at-least-32-characters-long";
process.env.JWT_ACCESS_TTL = "15m";
process.env.JWT_REFRESH_TTL_DAYS = "7";
process.env.COOKIE_SECURE = "false";
process.env.LOG_LEVEL = "silent";
process.env.UPLOAD_DIR = "../.local/test-uploads";
process.env.MAX_UPLOAD_BYTES = "2000000";
