import argon2 from "argon2";
import { DateTime } from "luxon";
import request from "supertest";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createApp } from "../../src/app.js";
import { prisma } from "../../src/config/prisma.js";

const app = createApp(); const password = "Phase6-Password-2026"; const auth = (token: string) => ({ Authorization: `Bearer ${token}` });
let adminToken = ""; let basicToken = ""; let foreignToken = ""; let businessId = ""; let userId = ""; let employeeId = ""; let serviceId = ""; let methodId = "";

async function resetAll() { await prisma.cashMovement.deleteMany(); await prisma.payment.deleteMany(); await prisma.cashRegister.deleteMany(); await prisma.appointmentStatusEvent.deleteMany(); await prisma.appointment.deleteMany(); await prisma.scheduleBlock.deleteMany(); await prisma.employeeSchedule.deleteMany(); await prisma.employeeService.deleteMany(); await prisma.service.deleteMany(); await prisma.serviceCategory.deleteMany(); await prisma.employee.deleteMany(); await prisma.client.deleteMany(); await prisma.refreshSession.deleteMany(); await prisma.auditLog.deleteMany(); await prisma.userPermission.deleteMany(); await prisma.rolePermission.deleteMany(); await prisma.user.deleteMany(); await prisma.role.deleteMany(); await prisma.permission.deleteMany(); await prisma.paymentMethod.deleteMany(); await prisma.appSetting.deleteMany(); await prisma.business.deleteMany(); }

beforeAll(async () => {
  await resetAll();
  const permissions = await Promise.all(["dashboard.view", "statistics.view", "reports.view", "audit.view"].map((code) => prisma.permission.create({ data: { code, name: code } })));
  for (const suffix of ["A", "B"]) {
    const business = await prisma.business.create({ data: { name: `Analytics ${suffix}`, timezone: "America/Argentina/Cordoba", locale: "es-AR", currency: "ARS" } });
    const role = await prisma.role.create({ data: { businessId: business.id, code: "ADMIN", name: "Admin" } });
    await prisma.rolePermission.createMany({ data: permissions.map((permission) => ({ roleId: role.id, permissionId: permission.id })) });
    const user = await prisma.user.create({ data: { businessId: business.id, roleId: role.id, username: `analytics${suffix.toLowerCase()}`, email: `analytics${suffix.toLowerCase()}@test.local`, firstName: "Admin", lastName: suffix, passwordHash: await argon2.hash(password) } });
    const client = await prisma.client.create({ data: { businessId: business.id, firstName: suffix === "A" ? "=SUM(A1:A2)" : "Ajeno", lastName: "Cliente", createdAt: new Date("2026-08-10T12:00:00Z") } });
    const service = await prisma.service.create({ data: { businessId: business.id, name: `Corte ${suffix}`, price: "100.00", durationMinutes: 30 } });
    const employee = await prisma.employee.create({ data: { businessId: business.id, firstName: "Profesional", lastName: suffix } });
    await prisma.employeeService.create({ data: { employeeId: employee.id, serviceId: service.id } });
    const method = await prisma.paymentMethod.create({ data: { businessId: business.id, code: `CASH_${suffix}`, name: "Efectivo", kind: "CASH", isCash: true } });
    const register = await prisma.cashRegister.create({ data: { businessId: business.id, openedById: user.id, status: "ABIERTA", openingAmount: "0" } });
    const makeAppointment = async (startAt: Date, status: "COMPLETADO" | "CANCELADO" = "COMPLETADO") => prisma.appointment.create({ data: { businessId: business.id, clientId: client.id, serviceId: service.id, employeeId: employee.id, createdById: user.id, startAt, endAt: new Date(startAt.getTime() + 1_800_000), durationMinutes: 30, serviceName: service.name, price: "100.00", status, completedAt: status === "COMPLETADO" ? startAt : null } });
    const current = await makeAppointment(new Date("2026-08-10T12:00:00Z"));
    const previous = await makeAppointment(new Date("2026-08-03T12:00:00Z"));
    await makeAppointment(new Date("2026-08-11T12:00:00Z")); // histórico pre-Fase 5, sin pago
    await makeAppointment(new Date("2026-08-12T12:00:00Z"), "CANCELADO");
    await prisma.payment.create({ data: { businessId: business.id, appointmentId: current.id, paymentMethodId: method.id, cashRegisterId: register.id, recordedById: user.id, amount: suffix === "A" ? "100.10" : "9999.00", createdAt: new Date("2026-08-10T12:30:00Z") } });
    await prisma.payment.create({ data: { businessId: business.id, appointmentId: previous.id, paymentMethodId: method.id, cashRegisterId: register.id, recordedById: user.id, amount: "50.05", createdAt: new Date("2026-08-03T12:30:00Z") } });
    const reversedAppointment = await makeAppointment(new Date("2026-08-10T15:00:00Z"));
    await prisma.payment.create({ data: { businessId: business.id, appointmentId: reversedAppointment.id, paymentMethodId: method.id, cashRegisterId: register.id, recordedById: user.id, amount: "800.00", status: "REVERTIDO", reversedAt: new Date(), reversedById: user.id, reversalReason: "Test", createdAt: new Date("2026-08-10T15:30:00Z") } });
    await prisma.auditLog.create({ data: { businessId: business.id, userId: user.id, action: "PAYMENT_CREATED", entity: "Payment", entityId: current.id, metadata: { amount: "100.10", accessToken: "never-expose", nested: { passwordHash: "never-expose" } } } });
    if (suffix === "A") { businessId = business.id; userId = user.id; employeeId = employee.id; serviceId = service.id; methodId = method.id; }
  }
  const dashboard = permissions.find((item) => item.code === "dashboard.view")!; const role = await prisma.role.create({ data: { businessId, code: "BASIC", name: "Básico" } }); await prisma.rolePermission.create({ data: { roleId: role.id, permissionId: dashboard.id } }); await prisma.user.create({ data: { businessId, roleId: role.id, username: "analyticsbasic", email: "basic@analytics.local", firstName: "Basic", lastName: "User", passwordHash: await argon2.hash(password) } });
  adminToken = (await request(app).post("/api/auth/login").send({ identifier: "analyticsa", password })).body.data.accessToken; basicToken = (await request(app).post("/api/auth/login").send({ identifier: "analyticsbasic", password })).body.data.accessToken; foreignToken = (await request(app).post("/api/auth/login").send({ identifier: "analyticsb", password })).body.data.accessToken;
});
afterAll(async () => prisma.$disconnect());

describe("dashboard y permisos", () => {
  it("no entrega importes financieros a quien sólo tiene dashboard.view", async () => { const response = await request(app).get("/api/analytics/dashboard").set(auth(basicToken)); expect(response.status).toBe(200); expect(response.body.data).not.toHaveProperty("financial"); });
  it("protege estadísticas, reportes y auditoría en backend", async () => { expect((await request(app).get("/api/analytics/overview?from=2026-08-10&to=2026-08-12").set(auth(basicToken))).status).toBe(403); expect((await request(app).get("/api/reports/sales?from=2026-08-10&to=2026-08-12").set(auth(basicToken))).status).toBe(403); expect((await request(app).get("/api/audit?from=2026-08-10&to=2026-08-12").set(auth(basicToken))).status).toBe(403); });
});

describe("estadísticas y fuentes de verdad", () => {
  it("suma únicamente Payment REGISTRADO con Decimal", async () => { const response = await request(app).get("/api/analytics/overview?from=2026-08-10&to=2026-08-12").set(auth(adminToken)); expect(response.status).toBe(200); expect(response.body.data.current).toMatchObject({ sales: "100.10", paymentCount: 1, averageTicket: "100.10", cancelledCount: 1 }); });
  it("no fabrica ventas para COMPLETADO sin pago ni suma REVERTIDO", async () => { const response = await request(app).get("/api/reports/sales?from=2026-08-10&to=2026-08-12").set(auth(adminToken)); expect(response.body.data.meta.total).toBe(1); expect(response.body.data.items[0].amount).toBe("100.10"); });
  it("compara contra el período anterior equivalente", async () => { const response = await request(app).get("/api/analytics/overview?from=2026-08-10&to=2026-08-10").set(auth(adminToken)); expect(response.body.data.period).toMatchObject({ previousFrom: "2026-08-09", previousTo: "2026-08-09" }); expect(response.body.data.comparison.sales).toBeNull(); });
  it("rellena días sin actividad y agrupa por zona IANA", async () => { const response = await request(app).get("/api/analytics/timeseries?from=2026-08-09&to=2026-08-11").set(auth(adminToken)); expect(response.body.data.points).toHaveLength(3); expect(response.body.data.points.map((item: { sales: string }) => item.sales)).toEqual(["0.00", "100.10", "0.00"]); });
  it("genera rankings de servicios, profesionales y métodos", async () => { const response = await request(app).get(`/api/analytics/rankings?from=2026-08-10&to=2026-08-12&employeeId=${employeeId}&serviceId=${serviceId}`).set(auth(adminToken)); expect(response.status).toBe(200); expect(response.body.data.services[0]).toMatchObject({ sales: "100.10", count: 1 }); expect(response.body.data.paymentMethods[0].percentage).toBe("100.0"); });
  it("aísla estrictamente los negocios", async () => { const own = await request(app).get("/api/analytics/overview?from=2026-08-10&to=2026-08-12").set(auth(adminToken)); const foreign = await request(app).get("/api/analytics/overview?from=2026-08-10&to=2026-08-12").set(auth(foreignToken)); expect(own.body.data.current.sales).toBe("100.10"); expect(foreign.body.data.current.sales).toBe("9999.00"); });
  it("rechaza rangos mayores a 366 días", async () => { const response = await request(app).get("/api/analytics/overview?from=2025-01-01&to=2026-08-12").set(auth(adminToken)); expect(response.status).toBe(400); expect(response.body.code).toBe("DATE_RANGE_TOO_LARGE"); });
});

describe("reportes, CSV y auditoría", () => {
  it("pagina y filtra reportes en backend", async () => { const response = await request(app).get(`/api/reports/sales?from=2026-08-01&to=2026-08-12&page=1&pageSize=1&paymentMethodId=${methodId}`).set(auth(adminToken)); expect(response.body.data.meta).toMatchObject({ page: 1, pageSize: 1, total: 2, totalPages: 2 }); });
  it("exporta CSV UTF-8 con BOM, separador, monto numérico y neutralización de fórmulas", async () => { const response = await request(app).get("/api/reports/sales/export?from=2026-08-10&to=2026-08-10").set(auth(adminToken)); expect(response.status).toBe(200); expect(response.headers["content-type"]).toContain("text/csv"); expect(response.headers["content-disposition"]).toContain("borkin-sales-2026-08-10-a-2026-08-10.csv"); expect(response.text.charCodeAt(0)).toBe(0xfeff); expect(response.text).toContain(";\"'=SUM(A1:A2) Cliente\""); expect(response.text).toContain(";100.10"); });
  it("sanea metadata sensible y filtra auditoría", async () => { const response = await request(app).get(`/api/audit?from=2026-08-01&to=${DateTime.now().plus({ days: 1 }).toISODate()}&userId=${userId}&action=PAYMENT_CREATED`).set(auth(adminToken)); expect(response.status).toBe(200); const serialized = JSON.stringify(response.body.data.items); expect(serialized).not.toContain("never-expose"); expect(serialized).toContain("[PROTEGIDO]"); });
  it("ventas distingue precio original, monto cobrado y usuario en API y CSV", async () => { const response = await request(app).get("/api/reports/sales?from=2026-08-10&to=2026-08-10").set(auth(adminToken)); expect(response.body.data.items[0]).toMatchObject({ originalPrice: "100.00", amount: "100.10", recordedByName: "Admin A" }); const csv = await request(app).get("/api/reports/sales/export?from=2026-08-10&to=2026-08-10").set(auth(adminToken)); expect(csv.text).toContain('"Precio original";"Monto cobrado";"Usuario"'); expect(csv.text).toContain(";100.00;100.10;\"Admin A\""); });
  it("turno pre-Fase 5 representa ausencia de Payment sin fabricar cero", async () => { const response = await request(app).get("/api/reports/appointments?from=2026-08-11&to=2026-08-11").set(auth(adminToken)); const historical = response.body.data.items.find((item: { serviceName: string }) => item.serviceName === "Corte A"); expect(historical).toMatchObject({ price: "100.00", paidAmount: null }); const csv = await request(app).get("/api/reports/appointments/export?from=2026-08-11&to=2026-08-11").set(auth(adminToken)); expect(csv.text).toContain('"Precio histórico";"Monto cobrado"'); expect(csv.text).toContain('100.00;"Sin Payment"'); });
  it("CSV de clientes conserva turnos y última visita sin notas", async () => { const response = await request(app).get("/api/reports/clients/export?from=2026-08-10&to=2026-08-10").set(auth(adminToken)); expect(response.text).toContain('"Turnos";"Última visita";"Estado"'); expect(response.text).toContain("11/08/2026"); expect(response.text).not.toContain("notes"); });
  it("movimientos incluye usuario y referencia legible de caja en API y CSV", async () => { const register = await prisma.cashRegister.findFirstOrThrow({ where: { businessId } }); const movement = await prisma.cashMovement.create({ data: { businessId, cashRegisterId: register.id, paymentMethodId: methodId, createdById: userId, type: "INGRESO_MANUAL", concept: "Ajuste QA", amount: "25.00", occurredAt: new Date("2026-08-14T12:00:00Z") } }); try { const response = await request(app).get("/api/reports/movements?from=2026-08-14&to=2026-08-14").set(auth(adminToken)); expect(response.body.data.items[0]).toMatchObject({ createdByName: "Admin A", cashRegister: { id: register.id } }); const csv = await request(app).get("/api/reports/movements/export?from=2026-08-14&to=2026-08-14").set(auth(adminToken)); expect(csv.text).toContain('"Usuario";"Caja abierta";"Importe"'); expect(csv.text).toContain('"Admin A"'); } finally { await prisma.cashMovement.delete({ where: { id: movement.id } }); } });
  it("los reportes mantienen aislamiento por businessId", async () => { const own = await request(app).get("/api/reports/sales?from=2026-08-10&to=2026-08-10").set(auth(adminToken)); const foreign = await request(app).get("/api/reports/sales?from=2026-08-10&to=2026-08-10").set(auth(foreignToken)); expect(own.body.data.items.map((item: { amount: string }) => item.amount)).toEqual(["100.10"]); expect(foreign.body.data.items.map((item: { amount: string }) => item.amount)).toEqual(["9999.00"]); });
  it("agrupa un servicio renombrado por ID en ranking, reporte, total y CSV", async () => {
    const client = await prisma.client.findFirstOrThrow({ where: { businessId } }); const register = await prisma.cashRegister.findFirstOrThrow({ where: { businessId } });
    const service = await prisma.service.create({ data: { businessId, name: "Corte", price: "120.00", durationMinutes: 30 } }); await prisma.employeeService.create({ data: { employeeId, serviceId: service.id } });
    const createPaid = async (day: number, snapshot: string, amount: string) => { const startAt = new Date(`2026-08-${day}T12:00:00Z`); const appointment = await prisma.appointment.create({ data: { businessId, clientId: client.id, serviceId: service.id, employeeId, createdById: userId, startAt, endAt: new Date(startAt.getTime() + 1_800_000), durationMinutes: 30, serviceName: snapshot, price: "120.00", status: "COMPLETADO", completedAt: startAt } }); return prisma.payment.create({ data: { businessId, appointmentId: appointment.id, paymentMethodId: methodId, cashRegisterId: register.id, recordedById: userId, amount, createdAt: new Date(`2026-08-${day}T12:30:00Z`) } }); };
    try {
      await createPaid(20, "Corte", "120.00"); await prisma.service.update({ where: { id: service.id }, data: { name: "Corte premium" } }); await createPaid(21, "Corte premium", "80.00");
      const ranking = await request(app).get(`/api/analytics/rankings?from=2026-08-20&to=2026-08-21&serviceId=${service.id}`).set(auth(adminToken)); expect(ranking.body.data.services).toEqual([{ id: service.id, name: "Corte premium", sales: "200.00", count: 2 }]);
      const report = await request(app).get(`/api/reports/services?from=2026-08-20&to=2026-08-21&serviceId=${service.id}`).set(auth(adminToken)); expect(report.body.data.items).toEqual([{ id: service.id, name: "Corte premium", count: 2, amount: "200.00", average: "100.00" }]); expect(report.body.data.meta.total).toBe(report.body.data.items.length); expect(report.body.data.meta.total).toBe(1);
      const csv = await request(app).get(`/api/reports/services/export?from=2026-08-20&to=2026-08-21&serviceId=${service.id}`).set(auth(adminToken)); expect(csv.text).toContain('"Corte premium";"2";200.00;100.00'); expect(csv.text.trim().split("\r\n")).toHaveLength(2);
    } finally { const turns = await prisma.appointment.findMany({ where: { serviceId: service.id }, select: { id: true } }); await prisma.payment.deleteMany({ where: { appointmentId: { in: turns.map((item) => item.id) } } }); await prisma.appointment.deleteMany({ where: { serviceId: service.id } }); await prisma.employeeService.deleteMany({ where: { serviceId: service.id } }); await prisma.service.delete({ where: { id: service.id } }); }
  });
});
