import argon2 from "argon2";
import { Settings } from "luxon";
import request from "supertest";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createApp } from "../../src/app.js";
import { prisma } from "../../src/config/prisma.js";

const app = createApp(); const password = "Phase4-Password-2026"; const auth = (token: string) => ({ Authorization: `Bearer ${token}` });
const realLuxonNow = Settings.now; const fixedNow = Date.parse("2026-08-17T10:00:00.000Z");
let token = ""; let foreignToken = ""; let limitedToken = ""; let businessId = ""; let foreignBusinessId = ""; let clientId = ""; let foreignClientId = ""; let inactiveClientId = ""; let serviceId = ""; let inactiveServiceId = ""; let employeeId = ""; let employee2Id = ""; let foreignEmployeeId = "";
const date = "2026-08-17";
const body = (time: string, overrides: Record<string, unknown> = {}) => ({ clientId, serviceId, employeeId, date, time, ...overrides });

async function resetDatabase() {
  await prisma.cashMovement.deleteMany(); await prisma.payment.deleteMany(); await prisma.cashRegister.deleteMany(); await prisma.appointmentStatusEvent.deleteMany(); await prisma.appointment.deleteMany(); await prisma.scheduleBlock.deleteMany(); await prisma.employeeSchedule.deleteMany(); await prisma.employeeService.deleteMany(); await prisma.service.deleteMany(); await prisma.serviceCategory.deleteMany(); await prisma.employee.deleteMany(); await prisma.client.deleteMany(); await prisma.refreshSession.deleteMany(); await prisma.auditLog.deleteMany(); await prisma.userPermission.deleteMany(); await prisma.rolePermission.deleteMany(); await prisma.user.deleteMany(); await prisma.role.deleteMany(); await prisma.permission.deleteMany(); await prisma.paymentMethod.deleteMany(); await prisma.appSetting.deleteMany(); await prisma.business.deleteMany();
}

beforeAll(async () => {
  Settings.now = () => fixedNow;
  await resetDatabase();
  const permissions = await Promise.all(["appointments.view", "appointments.create", "appointments.edit", "appointments.cancel", "clients.view"].map((code) => prisma.permission.create({ data: { code, name: code } })));
  for (const suffix of ["A", "B"] as const) {
    const business = await prisma.business.create({ data: { name: `Agenda ${suffix}`, timezone: "America/Argentina/Cordoba" } });
    const role = await prisma.role.create({ data: { businessId: business.id, code: "ADMIN", name: "Admin" } });
    await prisma.rolePermission.createMany({ data: permissions.map((permission) => ({ roleId: role.id, permissionId: permission.id })) });
    await prisma.user.create({ data: { businessId: business.id, roleId: role.id, username: `agenda${suffix.toLowerCase()}`, email: `agenda${suffix.toLowerCase()}@test.local`, firstName: "Agenda", lastName: suffix, passwordHash: await argon2.hash(password) } });
    const client = await prisma.client.create({ data: { businessId: business.id, firstName: `Cliente ${suffix}`, active: true } });
    const category = await prisma.serviceCategory.create({ data: { businessId: business.id, name: `Categoría ${suffix}` } });
    const service = await prisma.service.create({ data: { businessId: business.id, categoryId: category.id, name: `Corte ${suffix}`, price: "1000.00", durationMinutes: 45 } });
    const employee = await prisma.employee.create({ data: { businessId: business.id, firstName: "Profesional", lastName: suffix } });
    await prisma.employeeService.create({ data: { employeeId: employee.id, serviceId: service.id } });
    await prisma.employeeSchedule.createMany({ data: [1,2,3,4,5].map((dayOfWeek) => ({ employeeId: employee.id, dayOfWeek, startMinute: 540, endMinute: 1080 })) });
    if (suffix === "A") { businessId = business.id; clientId = client.id; serviceId = service.id; employeeId = employee.id; }
    else { foreignBusinessId = business.id; foreignClientId = client.id; foreignEmployeeId = employee.id; }
  }
  const category = await prisma.serviceCategory.findFirstOrThrow({ where: { businessId } });
  inactiveClientId = (await prisma.client.create({ data: { businessId, firstName: "Inactivo", active: false } })).id;
  inactiveServiceId = (await prisma.service.create({ data: { businessId, categoryId: category.id, name: "Inactivo", price: "1", durationMinutes: 30, active: false } })).id;
  employee2Id = (await prisma.employee.create({ data: { businessId, firstName: "Segundo", lastName: "Profesional" } })).id;
  await prisma.employeeSchedule.create({ data: { employeeId: employee2Id, dayOfWeek: 1, startMinute: 540, endMinute: 1080 } });
  const limitedRole = await prisma.role.create({ data: { businessId, code: "LIMITED", name: "Sin permisos" } });
  await prisma.user.create({ data: { businessId, roleId: limitedRole.id, username: "agendalimited", email: "agendalimited@test.local", firstName: "Sin", lastName: "Permisos", passwordHash: await argon2.hash(password) } });
  token = (await request(app).post("/api/auth/login").send({ identifier: "agendaa", password })).body.data.accessToken;
  foreignToken = (await request(app).post("/api/auth/login").send({ identifier: "agendab", password })).body.data.accessToken;
  limitedToken = (await request(app).post("/api/auth/login").send({ identifier: "agendalimited", password })).body.data.accessToken;
});

afterAll(async () => { Settings.now = realLuxonNow; await prisma.$disconnect(); });

describe("disponibilidad y tiempo", () => {
  it("genera slots cada 15 minutos y respeta límites con duración de 45", async () => { const response = await request(app).get(`/api/appointments/availability?serviceId=${serviceId}&employeeId=${employeeId}&date=${date}`).set(auth(token)); expect(response.status).toBe(200); expect(response.body.data.slots[0]).toMatchObject({ time: "09:00", durationMinutes: 45 }); expect(response.body.data.slots.at(-1).time).toBe("17:15"); expect(response.body.data.slotMinutes).toBe(15); });
  it("devuelve lista vacía para disponibilidad de una fecha local pasada", async () => { const response = await request(app).get(`/api/appointments/availability?serviceId=${serviceId}&employeeId=${employeeId}&date=2026-08-16`).set(auth(token)); expect(response.status).toBe(200); expect(response.body.data.slots).toEqual([]); });
  it("no devuelve slots anteriores al instante actual cuando consulta hoy", async () => { const previous = Settings.now; const now = Date.parse("2026-08-17T13:07:00.000Z"); Settings.now = () => now; try { const response = await request(app).get(`/api/appointments/availability?serviceId=${serviceId}&employeeId=${employeeId}&date=${date}`).set(auth(token)); expect(response.status).toBe(200); expect(response.body.data.slots.length).toBeGreaterThan(0); expect(response.body.data.slots.every((slot: { startAt: string }) => Date.parse(slot.startAt) >= now)).toBe(true); expect(response.body.data.slots[0].time).toBe("10:15"); } finally { Settings.now = previous; } });
  it("rechaza crear ayer con el error operativo acordado", async () => { const response = await request(app).post("/api/appointments").set(auth(token)).send(body("12:00", { date: "2026-08-16" })); expect(response.status).toBe(400); expect(response.body).toMatchObject({ code: "APPOINTMENT_IN_PAST", message: "No se pueden crear turnos en una fecha u horario pasado." }); });
  it("rechaza crear hoy en una hora pasada", async () => { const response = await request(app).post("/api/appointments").set(auth(token)).send(body("06:45")); expect(response.status).toBe(400); expect(response.body.code).toBe("APPOINTMENT_IN_PAST"); });
  it("permite crear hoy en una hora futura", async () => { const response = await request(app).post("/api/appointments").set(auth(token)).send(body("09:00")); expect(response.status).toBe(201); });
  it("permite crear mañana", async () => { const response = await request(app).post("/api/appointments").set(auth(token)).send(body("09:00", { date: "2026-08-18" })); expect(response.status).toBe(201); });
  it("usa el día local aunque UTC todavía esté en el día anterior", async () => { const previous = Settings.now; await prisma.business.update({ where: { id: businessId }, data: { timezone: "Asia/Tokyo" } }); Settings.now = () => Date.parse("2026-08-16T18:30:00.000Z"); try { const response = await request(app).post("/api/appointments").set(auth(token)).send(body("09:00")); expect(response.status).toBe(201); expect(response.body.data.startAt).toBe("2026-08-17T00:00:00.000Z"); } finally { Settings.now = previous; await prisma.business.update({ where: { id: businessId }, data: { timezone: "America/Argentina/Cordoba" } }); } });
  it("interpreta 10:00 en la zona del negocio y almacena UTC", async () => { const response = await request(app).post("/api/appointments").set(auth(token)).send(body("10:00")); expect(response.status).toBe(201); expect(response.body.data.startAt).toBe("2026-08-17T13:00:00.000Z"); expect(response.body.data.serviceName).toBe("Corte A"); });
  it("remueve de disponibilidad cualquier slot que intersecta un turno", async () => { const response = await request(app).get(`/api/appointments/availability?serviceId=${serviceId}&employeeId=${employeeId}&date=${date}`).set(auth(token)); const times = response.body.data.slots.map((slot: { time: string }) => slot.time); expect(times).not.toContain("09:30"); expect(times).not.toContain("10:00"); expect(times).not.toContain("10:30"); expect(times).toContain("10:45"); });
  it("rechaza fuera de jornada y acepta el borde final exacto", async () => { expect((await request(app).post("/api/appointments").set(auth(token)).send(body("08:45"))).body.code).toBe("OUTSIDE_WORKING_HOURS"); expect((await request(app).post("/api/appointments").set(auth(token)).send(body("17:15"))).status).toBe(201); expect((await request(app).post("/api/appointments").set(auth(token)).send(body("17:30"))).status).toBe(409); });
});

describe("solapamientos, adyacencia, bloqueos y concurrencia", () => {
  it("rechaza solapamiento parcial, interno y envolvente", async () => { for (const time of ["09:45", "10:15"]) { const response = await request(app).post("/api/appointments").set(auth(token)).send(body(time)); expect(response.status).toBe(409); expect(response.body.code).toBe("APPOINTMENT_CONFLICT"); } });
  it("permite adyacencia y el mismo horario con otro profesional compatible", async () => { expect((await request(app).post("/api/appointments").set(auth(token)).send(body("10:45"))).status).toBe(201); await prisma.employeeService.create({ data: { employeeId: employee2Id, serviceId } }); expect((await request(app).post("/api/appointments").set(auth(token)).send(body("10:00", { employeeId: employee2Id }))).status).toBe(201); });
  it("un bloqueo parcial impide crear y desaparece de slots", async () => { const startAt = new Date("2026-08-17T18:00:00.000Z"); const block = await prisma.scheduleBlock.create({ data: { businessId, employeeId, startAt, endAt: new Date("2026-08-17T19:00:00.000Z"), reason: "AUSENCIA" } }); const response = await request(app).post("/api/appointments").set(auth(token)).send(body("15:00")); expect(response.status).toBe(409); expect(response.body.code).toBe("SCHEDULE_BLOCK_CONFLICT"); await prisma.scheduleBlock.update({ where: { id: block.id }, data: { active: false, deletedAt: new Date() } }); });
  it("día completo y rango de fechas bloquean intervalos", async () => { const blocks = await prisma.scheduleBlock.createMany({ data: [{ businessId, employeeId, startAt: new Date("2026-08-18T03:00:00Z"), endAt: new Date("2026-08-19T03:00:00Z"), allDay: true, reason: "VACACIONES" }, { businessId, employeeId, startAt: new Date("2026-08-19T03:00:00Z"), endAt: new Date("2026-08-21T03:00:00Z"), allDay: true, reason: "VACACIONES" }] }); expect(blocks.count).toBe(2); for (const blockedDate of ["2026-08-18", "2026-08-20"]) expect((await request(app).post("/api/appointments").set(auth(token)).send(body("12:00", { date: blockedDate }))).body.code).toBe("SCHEDULE_BLOCK_CONFLICT"); });
  it("serializa dos creaciones simultáneas: exactamente una gana y otra recibe 409", async () => { const payload = body("12:00"); const responses = await Promise.all([request(app).post("/api/appointments").set(auth(token)).send(payload), request(app).post("/api/appointments").set(auth(token)).send(payload)]); expect(responses.map((response) => response.status).sort()).toEqual([201, 409]); expect(await prisma.appointment.count({ where: { businessId, employeeId, startAt: new Date("2026-08-17T15:00:00Z") } })).toBe(1); });
});

describe("cancelación, reprogramación y estados", () => {
  it("una edición de notas no recalcula el snapshot histórico del servicio", async () => { const created = await request(app).post("/api/appointments").set(auth(token)).send(body("11:00", { date: "2026-08-21" })); expect(created.status).toBe(201); const snapshot = { price: created.body.data.price, durationMinutes: created.body.data.durationMinutes, serviceName: created.body.data.serviceName }; await prisma.service.update({ where: { id: serviceId }, data: { price: "9999.00", durationMinutes: 60 } }); const updated = await request(app).patch(`/api/appointments/${created.body.data.id}`).set(auth(token)).send({ notes: "Sólo cambia la nota" }); expect(updated.body.data).toMatchObject({ ...snapshot, notes: "Sólo cambia la nota" }); await prisma.service.update({ where: { id: serviceId }, data: { price: "1000.00", durationMinutes: 45 } }); });
  it("cancelar exige motivo y libera el horario", async () => { const created = await request(app).post("/api/appointments").set(auth(token)).send(body("13:00")); expect((await request(app).post(`/api/appointments/${created.body.data.id}/cancel`).set(auth(token)).send({})).status).toBe(400); const cancelled = await request(app).post(`/api/appointments/${created.body.data.id}/cancel`).set(auth(token)).send({ reason: "Cliente avisó" }); expect(cancelled.body.data.status).toBe("CANCELADO"); expect((await request(app).post("/api/appointments").set(auth(token)).send(body("13:00"))).status).toBe(201); });
  it("rechaza reprogramar un turno a una fecha pasada", async () => { const created = await request(app).post("/api/appointments").set(auth(token)).send(body("14:00", { date: "2026-08-21" })); expect(created.status).toBe(201); const response = await request(app).post(`/api/appointments/${created.body.data.id}/reschedule`).set(auth(token)).send({ date: "2026-08-16", time: "14:00" }); expect(response.status).toBe(400); expect(response.body.code).toBe("APPOINTMENT_IN_PAST"); });
  it("reprograma a un horario libre y rechaza ocupado, bloqueado o fuera de jornada", async () => { const created = await request(app).post("/api/appointments").set(auth(token)).send(body("14:00")); expect((await request(app).post(`/api/appointments/${created.body.data.id}/reschedule`).set(auth(token)).send({ date, time: "14:45" })).status).toBe(200); expect((await request(app).post(`/api/appointments/${created.body.data.id}/reschedule`).set(auth(token)).send({ date, time: "12:00" })).body.code).toBe("APPOINTMENT_CONFLICT"); expect((await request(app).post(`/api/appointments/${created.body.data.id}/reschedule`).set(auth(token)).send({ date, time: "08:00" })).body.code).toBe("OUTSIDE_WORKING_HOURS"); });
  it("aplica la máquina de estados y desde Fase 5 exige cobro para completar", async () => { const created = await request(app).post("/api/appointments").set(auth(token)).send(body("16:00")); const id = created.body.data.id; expect((await request(app).post(`/api/appointments/${id}/confirm`).set(auth(token)).send()).body.data.status).toBe("CONFIRMADO"); expect((await request(app).post(`/api/appointments/${id}/start`).set(auth(token)).send()).body.data.status).toBe("EN_CURSO"); expect((await request(app).post(`/api/appointments/${id}/cancel`).set(auth(token)).send({ reason: "No permitido" })).body.code).toBe("INVALID_STATUS_TRANSITION"); expect((await request(app).post(`/api/appointments/${id}/complete`).set(auth(token)).send()).body.code).toBe("PAYMENT_REQUIRED"); expect(await prisma.appointmentStatusEvent.count({ where: { appointmentId: id } })).toBe(3); });
  it("completado y ausente son finales e inmutables", async () => { const created = await request(app).post("/api/appointments").set(auth(token)).send(body("09:00", { date: "2026-08-21" })); const id = created.body.data.id; expect((await request(app).post(`/api/appointments/${id}/no-show`).set(auth(token)).send({ reason: "No asistió" })).body.data.status).toBe("AUSENTE"); expect((await request(app).patch(`/api/appointments/${id}`).set(auth(token)).send({ notes: "alteración" })).body.code).toBe("APPOINTMENT_IMMUTABLE"); expect((await request(app).post(`/api/appointments/${id}/start`).set(auth(token)).send()).body.code).toBe("INVALID_STATUS_TRANSITION"); });
});

describe("relaciones, aislamiento y permisos", () => {
  it("rechaza UUID inválido en todos los paths de turno antes de Prisma", async () => { const responses = [await request(app).get("/api/appointments/not-a-uuid").set(auth(token)), await request(app).patch("/api/appointments/not-a-uuid").set(auth(token)).send({ notes: "x" }), await request(app).post("/api/appointments/not-a-uuid/confirm").set(auth(token)).send()]; for (const response of responses) { expect(response.status).toBe(400); expect(response.body.code).toBe("VALIDATION_ERROR"); } });
  it("rechaza serviceId inválido en disponibilidad y opciones", async () => { for (const path of [`/api/appointments/availability?serviceId=abc&employeeId=${employeeId}&date=${date}`, "/api/appointments/options?serviceId=abc"]) { const response = await request(app).get(path).set(auth(token)); expect(response.status).toBe(400); expect(response.body.code).toBe("VALIDATION_ERROR"); } });
  it("rechaza employeeId inválido en disponibilidad", async () => { const response = await request(app).get(`/api/appointments/availability?serviceId=${serviceId}&employeeId=xyz&date=${date}`).set(auth(token)); expect(response.status).toBe(400); expect(response.body.code).toBe("VALIDATION_ERROR"); });
  it("rechaza employeeId inválido en el filtro de agenda", async () => { const response = await request(app).get(`/api/appointments?from=${date}&to=${date}&employeeId=no-uuid`).set(auth(token)); expect(response.status).toBe(400); expect(response.body.code).toBe("VALIDATION_ERROR"); });
  it("rechaza cliente, servicio o profesional inactivo/ajeno y asignación incompatible", async () => { expect((await request(app).post("/api/appointments").set(auth(token)).send(body("11:00", { clientId: inactiveClientId }))).body.code).toBe("CLIENT_NOT_AVAILABLE"); expect((await request(app).post("/api/appointments").set(auth(token)).send(body("11:00", { serviceId: inactiveServiceId }))).body.code).toBe("SERVICE_NOT_AVAILABLE"); expect((await request(app).post("/api/appointments").set(auth(token)).send(body("11:00", { employeeId: foreignEmployeeId }))).body.code).toBe("EMPLOYEE_NOT_AVAILABLE"); await prisma.employeeService.delete({ where: { employeeId_serviceId: { employeeId: employee2Id, serviceId } } }); expect((await request(app).post("/api/appointments").set(auth(token)).send(body("11:00", { employeeId: employee2Id }))).body.code).toBe("EMPLOYEE_SERVICE_MISMATCH"); });
  it("no permite usar relaciones de otro negocio ni leer su turno", async () => { expect((await request(app).post("/api/appointments").set(auth(token)).send(body("11:00", { clientId: foreignClientId }))).status).toBe(404); const foreignService = await prisma.service.findFirstOrThrow({ where: { businessId: foreignBusinessId } }); const foreign = await request(app).post("/api/appointments").set(auth(foreignToken)).send({ clientId: foreignClientId, serviceId: foreignService.id, employeeId: foreignEmployeeId, date, time: "11:00" }); expect(foreign.status).toBe(201); expect((await request(app).get(`/api/appointments/${foreign.body.data.id}`).set(auth(token))).status).toBe(404); });
  it("exige permisos backend y limita el rango de listado a 93 días", async () => { expect((await request(app).get(`/api/appointments?from=${date}&to=${date}`).set(auth(limitedToken))).status).toBe(403); expect((await request(app).post("/api/appointments").set(auth(limitedToken)).send(body("11:00"))).status).toBe(403); expect((await request(app).get("/api/appointments?from=2026-01-01&to=2026-04-03").set(auth(token))).status).toBe(200); expect((await request(app).get("/api/appointments?from=2026-01-01&to=2026-04-04").set(auth(token))).status).toBe(400); });
  it("lista turnos y bloqueos del rango sin datos de otro negocio", async () => { const response = await request(app).get("/api/appointments?from=2026-08-17&to=2026-08-21").set(auth(token)); expect(response.status).toBe(200); expect(response.body.data.appointments.length).toBeGreaterThan(0); expect(response.body.data.appointments.every((item: { client: { firstName: string } }) => item.client.firstName !== "Cliente B")).toBe(true); expect(response.body.data.blocks).toHaveLength(2); });
});

describe("historial de turnos del cliente", () => {
  it("devuelve empty state paginado para un cliente sin turnos", async () => { const response = await request(app).get(`/api/clients/${inactiveClientId}/appointments`).set(auth(token)); expect(response.status).toBe(200); expect(response.body.data).toMatchObject({ items: [], meta: { page: 1, total: 0 }, summary: { appointmentCount: 0, completedCount: 0, lastVisit: null, nextAppointment: null } }); });
  it("devuelve varios turnos con snapshots y orden descendente", async () => { const response = await request(app).get(`/api/clients/${clientId}/appointments?page=1&pageSize=50`).set(auth(token)); expect(response.status).toBe(200); expect(response.body.data.items.length).toBeGreaterThan(2); const starts = response.body.data.items.map((item: { startAt: string }) => new Date(item.startAt).getTime()); expect(starts).toEqual([...starts].sort((a, b) => b - a)); expect(response.body.data.items[0]).toMatchObject({ serviceName: "Corte A", employee: { firstName: "Profesional" } }); expect(response.body.data.items[0]).toHaveProperty("price"); });
  it("pagina el historial y no descarga todos los turnos", async () => { const first = await request(app).get(`/api/clients/${clientId}/appointments?page=1&pageSize=2`).set(auth(token)); const second = await request(app).get(`/api/clients/${clientId}/appointments?page=2&pageSize=2`).set(auth(token)); expect(first.body.data.items).toHaveLength(2); expect(first.body.data.meta.totalPages).toBeGreaterThan(1); expect(second.body.data.items[0].id).not.toBe(first.body.data.items[0].id); });
  it("business A no accede al historial del cliente de business B", async () => { const response = await request(app).get(`/api/clients/${foreignClientId}/appointments`).set(auth(token)); expect(response.status).toBe(404); expect(response.body.code).toBe("CLIENT_NOT_FOUND"); });
});
