import { Router } from "express";
import { health } from "../controllers/health.controller.js";
import { accessRouter, userRouter } from "./user.routes.js";
import { authRouter } from "./auth.routes.js";
import { blockRouter, categoryRouter, employeeRouter, serviceRouter, settingsRouter } from "./phase2.routes.js";
import { clientRouter } from "./client.routes.js";
import { appointmentRouter } from "./appointment.routes.js";

export const apiRouter = Router();
apiRouter.get("/health", health);
apiRouter.use("/auth", authRouter);
apiRouter.use("/users", userRouter);
apiRouter.use("/access", accessRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/service-categories", categoryRouter);
apiRouter.use("/services", serviceRouter);
apiRouter.use("/employees", employeeRouter);
apiRouter.use("/schedule-blocks", blockRouter);
apiRouter.use("/clients", clientRouter);
apiRouter.use("/appointments", appointmentRouter);
