import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarClock, ChevronLeft, ChevronRight, Clock3, MessageCircle, Plus, UserRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { Field, Modal } from "../components/Modal";
import { useAuth } from "../hooks/useAuth";
import { apiRequest } from "../services/api/client";
import type { AgendaData, Appointment, AppointmentOptions, AppointmentStatus, Availability } from "../types/api";
import { agendaPath, appointmentError, calendarRange, clearAfterEmployeeOrDateChange, clearAfterServiceChange, clientOptionsPath, intervalIntersectsLocalDay, localDateKey, navigateAnchor, statusActions, todayKeyInZone, type CalendarView } from "../utils/appointments";
import { hasPermission } from "../utils/permissions";

const statusLabels: Record<AppointmentStatus, string> = { PENDIENTE: "Pendiente", CONFIRMADO: "Confirmado", EN_CURSO: "En curso", COMPLETADO: "Completado", CANCELADO: "Cancelado", AUSENTE: "Ausente" };
const statusClasses: Record<AppointmentStatus, string> = { PENDIENTE: "bg-amber-50 text-amber-700", CONFIRMADO: "bg-blue-50 text-blue-700", EN_CURSO: "bg-violet-50 text-violet-700", COMPLETADO: "bg-emerald-50 text-emerald-700", CANCELADO: "bg-slate-100 text-slate-500", AUSENTE: "bg-red-50 text-red-700" };
const clientName = (item: Appointment) => [item.client.firstName, item.client.lastName].filter(Boolean).join(" ");
const employeeName = (item: Appointment) => `${item.employee.firstName} ${item.employee.lastName}`;
const dayTitle = (date: string) => new Intl.DateTimeFormat("es-AR", { timeZone: "UTC", weekday: "short", day: "2-digit", month: "short" }).format(new Date(`${date}T00:00:00Z`));
const timeLabel = (iso: string, zone: string) => new Intl.DateTimeFormat("es-AR", { timeZone: zone, hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(iso));

export function AgendaPage() {
  const { user } = useAuth(); const queryClient = useQueryClient();
  const zone = user?.business.timezone ?? "UTC";
  const [view, setView] = useState<CalendarView>(() => typeof window !== "undefined" && window.innerWidth < 768 ? "day" : "week");
  const [anchor, setAnchor] = useState(() => todayKeyInZone(zone)); const [employeeId, setEmployeeId] = useState(""); const [creating, setCreating] = useState(false); const [selected, setSelected] = useState<Appointment | null>(null); const [editing, setEditing] = useState<"edit" | "reschedule" | null>(null);
  const range = useMemo(() => calendarRange(view, anchor), [view, anchor]);
  const options = useQuery({ queryKey: ["appointment-options"], queryFn: () => apiRequest<AppointmentOptions>("/appointments/options") });
  const agenda = useQuery({ queryKey: ["agenda", range.from, range.to, employeeId], queryFn: () => apiRequest<AgendaData>(agendaPath(range.from, range.to, employeeId)) });
  const refresh = async () => { await queryClient.invalidateQueries({ queryKey: ["agenda"] }); };
  if (!user) return null;
  return <div className="space-y-5"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="brand-text text-sm font-medium">Operación diaria</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Agenda</h1><p className="mt-2 text-slate-500">Turnos, disponibilidad y bloqueos en {user.business.timezone}.</p></div>{hasPermission(user.permissions, "appointments.create") && <button className="primary-button w-full sm:w-auto" onClick={() => setCreating(true)}><Plus size={18} />Nuevo turno</button>}</header>
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-2"><button className="secondary-button px-3" aria-label="Anterior" onClick={() => setAnchor(navigateAnchor(view, anchor, -1))}><ChevronLeft size={18} /></button><button className="secondary-button" onClick={() => setAnchor(todayKeyInZone(zone))}>Hoy</button><button className="secondary-button px-3" aria-label="Siguiente" onClick={() => setAnchor(navigateAnchor(view, anchor, 1))}><ChevronRight size={18} /></button><span className="ml-2 hidden text-sm font-semibold text-slate-700 sm:inline">{dayTitle(range.from)}{range.from !== range.to ? ` — ${dayTitle(range.to)}` : ""}</span></div><div className="flex flex-col gap-3 sm:flex-row"><select className="field min-w-52" aria-label="Filtrar profesional" value={employeeId} onChange={(event) => setEmployeeId(event.target.value)}><option value="">Todos los profesionales</option>{options.data?.employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.firstName} {employee.lastName}</option>)}</select><div className="grid grid-cols-3 rounded-xl bg-slate-100 p-1">{(["day", "week", "month"] as const).map((item) => <button key={item} className={`rounded-lg px-3 py-2 text-sm font-medium ${view === item ? "bg-white shadow-sm" : "text-slate-500"}`} onClick={() => setView(item)}>{item === "day" ? "Día" : item === "week" ? "Semana" : "Mes"}</button>)}</div></div></div>
      {agenda.isLoading ? <div className="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-4" aria-label="Cargando agenda">{[1,2,3,4].map((item) => <div key={item} className="h-40 animate-pulse rounded-xl bg-slate-100" />)}</div> : agenda.isError ? <div className="p-10 text-center"><p className="font-medium">No pudimos cargar la agenda.</p><p className="mt-2 text-sm text-slate-500">{appointmentError(agenda.error)}</p><button className="secondary-button mt-4" onClick={() => void agenda.refetch()}>Reintentar</button></div> : <CalendarGrid days={range.days} view={view} anchor={anchor} zone={zone} data={agenda.data ?? { appointments: [], blocks: [] }} onOpen={setSelected} onCreate={(date) => { setAnchor(date); setCreating(true); }} />}
    </section>
    {creating && <AppointmentForm title="Nuevo turno" initialDate={anchor} onClose={() => setCreating(false)} onSaved={async () => { setCreating(false); await refresh(); }} />}
    {selected && !editing && <AppointmentDetail item={selected} zone={zone} onClose={() => setSelected(null)} onEdit={(mode) => setEditing(mode)} onChanged={async (item) => { setSelected(item); await refresh(); }} />}
    {selected && editing && <AppointmentForm title={editing === "edit" ? "Editar turno" : "Reprogramar turno"} item={selected} rescheduleOnly={editing === "reschedule"} initialDate={localDateKey(selected.startAt, zone)} onClose={() => setEditing(null)} onSaved={async (item) => { setEditing(null); setSelected(item); await refresh(); }} />}
  </div>;
}

function CalendarGrid({ days, view, anchor, zone, data, onOpen, onCreate }: { days: string[]; view: CalendarView; anchor: string; zone: string; data: AgendaData; onOpen: (item: Appointment) => void; onCreate: (date: string) => void }) {
  return <div className={`grid divide-y divide-slate-100 ${view === "week" ? "md:grid-cols-7 md:divide-x md:divide-y-0" : view === "month" ? "sm:grid-cols-7" : "grid-cols-1"}`}>{days.map((day) => { const appointments = data.appointments.filter((item) => localDateKey(item.startAt, zone) === day); const blocks = data.blocks.filter((item) => intervalIntersectsLocalDay(item.startAt, item.endAt, day, zone)); const outside = view === "month" && day.slice(0, 7) !== anchor.slice(0, 7); return <section key={day} className={`min-h-36 p-2.5 ${view === "day" ? "sm:p-5" : ""} ${outside ? "bg-slate-50/70" : ""}`}><button className="mb-2 w-full text-left text-xs font-semibold uppercase tracking-wide text-slate-500" onClick={() => onCreate(day)}>{dayTitle(day)}</button><div className="space-y-2">{blocks.map((block) => <div key={block.id} className="rounded-lg border border-dashed border-slate-300 bg-slate-100 px-2 py-1.5 text-xs text-slate-600">Bloqueo · {block.customReason ?? block.reason.toLowerCase()}</div>)}{appointments.map((item) => <button key={item.id} className={`block w-full rounded-lg border-l-4 bg-white p-2 text-left shadow-sm ring-1 ring-slate-200 transition hover:shadow ${item.status === "CANCELADO" ? "opacity-55" : ""}`} style={{ borderLeftColor: item.employee.color }} onClick={() => onOpen(item)}><span className="block text-xs font-semibold">{timeLabel(item.startAt, zone)} · {clientName(item)}</span><span className="mt-1 block truncate text-xs text-slate-500">{item.serviceName} · {employeeName(item)}</span><span className={`mt-1.5 inline-block rounded-full px-1.5 py-0.5 text-[10px] font-medium ${statusClasses[item.status]}`}>{statusLabels[item.status]}</span></button>)}{!blocks.length && !appointments.length && <button className="w-full rounded-lg py-3 text-xs text-slate-300 hover:bg-slate-50 hover:text-slate-500" onClick={() => onCreate(day)}>Sin eventos</button>}</div></section>; })}</div>;
}

export type ClientOption = { id: string; fullName: string; phone: string | null };
export function ClientAutocomplete({ value, onChange }: { value: ClientOption | null; onChange: (value: ClientOption | null) => void }) {
  const [search, setSearch] = useState(value?.fullName ?? ""); const [debounced, setDebounced] = useState(""); const [open, setOpen] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => setDebounced(search.trim()), 300); return () => window.clearTimeout(timer); }, [search]);
  const results = useQuery({ queryKey: ["client-options-agenda", debounced], enabled: debounced.length >= 2 && (!value || debounced !== value.fullName), queryFn: () => apiRequest<ClientOption[]>(clientOptionsPath(debounced)) });
  const updateSearch = (next: string) => { setSearch(next); setOpen(true); if (value && next !== value.fullName) onChange(null); };
  const select = (client: ClientOption) => { onChange(client); setSearch(client.fullName); setDebounced(client.fullName); setOpen(false); };
  return <div className="relative sm:col-span-1"><label className="mb-2 block text-sm font-medium" htmlFor="appointment-client-search">Buscar cliente</label><div className="relative"><input id="appointment-client-search" className="field pr-16" role="combobox" aria-expanded={open} aria-controls="appointment-client-results" aria-autocomplete="list" placeholder="Nombre, apellido o teléfono…" value={search} onFocus={() => setOpen(true)} onChange={(event) => updateSearch(event.target.value)} />{search && <button type="button" className="absolute inset-y-0 right-0 px-3 text-xs font-medium text-slate-500" aria-label="Borrar cliente" onClick={() => { setSearch(""); setDebounced(""); setOpen(false); onChange(null); }}>Borrar</button>}</div>{value && <p className="mt-2 text-xs text-emerald-700">Seleccionado: {value.fullName}{value.phone ? ` · ${value.phone}` : ""}</p>}{open && debounced.length >= 2 && !value && <div id="appointment-client-results" role="listbox" className="absolute z-20 mt-2 max-h-56 w-full overflow-y-auto rounded-xl border border-slate-200 bg-white p-1 shadow-xl">{results.isFetching ? <p className="p-3 text-sm text-slate-500">Buscando…</p> : results.data?.length ? results.data.map((client) => <button key={client.id} type="button" role="option" aria-selected="false" className="block w-full rounded-lg px-3 py-2.5 text-left hover:bg-slate-50" onMouseDown={(event) => event.preventDefault()} onClick={() => select(client)}><span className="block text-sm font-medium">{client.fullName}</span>{client.phone && <span className="mt-0.5 block text-xs text-slate-500">{client.phone}</span>}</button>) : <p className="p-3 text-sm text-slate-500">No encontramos clientes activos.</p>}</div>}</div>;
}
function AppointmentForm({ title, item, rescheduleOnly = false, initialDate, onClose, onSaved }: { title: string; item?: Appointment; rescheduleOnly?: boolean; initialDate: string; onClose: () => void; onSaved: (item: Appointment) => Promise<void> }) {
  const { user } = useAuth(); const zone = user?.business.timezone ?? "UTC"; const initialTime = item ? timeLabel(item.startAt, zone) : "";
  const [selectedClient, setSelectedClient] = useState<ClientOption | null>(item ? { id: item.client.id, fullName: clientName(item), phone: item.client.phone } : null); const clientId = selectedClient?.id ?? ""; const [serviceId, setServiceId] = useState(item?.serviceId ?? ""); const [employeeId, setEmployeeId] = useState(item?.employeeId ?? ""); const [date, setDate] = useState(initialDate); const [time, setTime] = useState(initialTime); const [notes, setNotes] = useState(item?.notes ?? ""); const [error, setError] = useState("");
  const options = useQuery({ queryKey: ["appointment-options", serviceId], queryFn: () => apiRequest<AppointmentOptions>(`/appointments/options${serviceId ? `?serviceId=${serviceId}` : ""}`) });
  const availability = useQuery({ queryKey: ["availability", serviceId, employeeId, date, item?.id], enabled: Boolean(serviceId && employeeId && date), queryFn: () => apiRequest<Availability>(`/appointments/availability?serviceId=${serviceId}&employeeId=${employeeId}&date=${date}`) });
  const mutation = useMutation({ mutationFn: () => { if ((!rescheduleOnly && (!clientId || !serviceId)) || !employeeId || !date || !time) throw new Error("Completá cliente, servicio, profesional, fecha y horario."); const body = rescheduleOnly ? { employeeId, date, time } : { clientId, serviceId, employeeId, date, time, notes: notes || null }; const path = item ? (rescheduleOnly ? `/appointments/${item.id}/reschedule` : `/appointments/${item.id}`) : "/appointments"; return apiRequest<Appointment>(path, { method: item ? (rescheduleOnly ? "POST" : "PATCH") : "POST", body: JSON.stringify(body) }); }, onSuccess: async (saved) => { toast.success(item ? "Turno actualizado." : "Turno creado."); await onSaved(saved); }, onError: (value) => { const text = appointmentError(value); setError(text); toast.error(text); } });
  return <Modal title={title} onClose={onClose} width="max-w-3xl"><div className="grid gap-4 sm:grid-cols-2">{!rescheduleOnly && <><ClientAutocomplete value={selectedClient} onChange={setSelectedClient} /><Field label="Servicio"><select className="field" value={serviceId} onChange={(event) => { setServiceId(event.target.value); const cleared = clearAfterServiceChange(); setEmployeeId(cleared.employeeId); setTime(cleared.time); }}><option value="">Seleccionar servicio</option>{options.data?.services.map((service) => <option key={service.id} value={service.id}>{service.name} · {service.durationMinutes} min</option>)}</select></Field></>}
      <Field label="Profesional"><select className="field" value={employeeId} onChange={(event) => { setEmployeeId(event.target.value); setTime(clearAfterEmployeeOrDateChange().time); }}><option value="">Seleccionar profesional</option>{options.data?.employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.firstName} {employee.lastName}</option>)}</select></Field><Field label="Fecha"><input className="field" type="date" value={date} onChange={(event) => { setDate(event.target.value); setTime(clearAfterEmployeeOrDateChange().time); }} /></Field>
      <div className="sm:col-span-2"><span className="mb-2 block text-sm font-medium">Horarios disponibles</span>{availability.isFetching ? <p className="text-sm text-slate-500">Calculando disponibilidad…</p> : availability.data?.slots.length ? <div className="flex max-h-36 flex-wrap gap-2 overflow-y-auto rounded-xl border border-slate-200 p-3">{availability.data.slots.map((slot) => <button key={slot.startAt} type="button" className={`rounded-lg px-3 py-2 text-sm font-medium ${time === slot.time ? "brand-bg text-white" : "bg-slate-100 text-slate-700 hover:bg-slate-200"}`} onClick={() => setTime(slot.time)}>{slot.time}</button>)}</div> : serviceId && employeeId ? <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">No hay horarios disponibles para esta fecha.</p> : <p className="text-sm text-slate-500">Seleccioná servicio y profesional para ver los turnos.</p>}</div>
      {!rescheduleOnly && <div className="sm:col-span-2"><Field label="Notas"><textarea className="field min-h-24" value={notes} onChange={(event) => setNotes(event.target.value)} /></Field></div>}{error && <p className="field-error sm:col-span-2">{error}</p>}<div className="flex justify-end gap-3 border-t border-slate-100 pt-4 sm:col-span-2"><button className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? "Guardando…" : "Guardar"}</button></div></div></Modal>;
}

function AppointmentDetail({ item, zone, onClose, onEdit, onChanged }: { item: Appointment; zone: string; onClose: () => void; onEdit: (mode: "edit" | "reschedule") => void; onChanged: (item: Appointment) => Promise<void> }) {
  const { user } = useAuth(); const [reasonAction, setReasonAction] = useState<"cancel" | "no-show" | null>(null); const [reason, setReason] = useState("");
  const action = useMutation({ mutationFn: ({ name, reason }: { name: string; reason?: string }) => apiRequest<Appointment>(`/appointments/${item.id}/${name}`, { method: "POST", ...(reason !== undefined ? { body: JSON.stringify({ reason }) } : {}) }), onSuccess: async (saved) => { toast.success("Estado del turno actualizado."); setReasonAction(null); setReason(""); await onChanged(saved); }, onError: (value) => toast.error(appointmentError(value)) });
  const canEdit = user && hasPermission(user.permissions, "appointments.edit") && ["PENDIENTE", "CONFIRMADO"].includes(item.status); const actions = statusActions(item.status);
  const phone = (item.client.whatsapp ?? item.client.phoneNormalized ?? item.client.phone ?? "").replace(/\D/g, ""); const validPhone = phone.length >= 8 && phone.length <= 15;
  const whatsapp = () => { const message = `Hola ${item.client.firstName}, te recordamos tu turno en ${user?.business.name}: ${new Intl.DateTimeFormat("es-AR", { timeZone: zone, dateStyle: "full", timeStyle: "short" }).format(new Date(item.startAt))}, servicio ${item.serviceName}.`; window.open(`https://wa.me/${phone}?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer"); };
  return <><Modal title="Detalle del turno" onClose={onClose}><div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-semibold">{clientName(item)}</h3><p className="mt-1 text-sm text-slate-500">{item.serviceName} con {employeeName(item)}</p></div><span className={`rounded-full px-3 py-1 text-sm font-medium ${statusClasses[item.status]}`}>{statusLabels[item.status]}</span></div><dl className="grid gap-4 rounded-xl bg-slate-50 p-4 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Fecha y hora</dt><dd className="mt-1 font-medium">{new Intl.DateTimeFormat("es-AR", { timeZone: zone, dateStyle: "long", timeStyle: "short" }).format(new Date(item.startAt))}</dd></div><div><dt className="text-xs text-slate-500">Duración y precio</dt><dd className="mt-1 font-medium">{item.durationMinutes} min · ${Number(item.price).toLocaleString("es-AR")}</dd></div>{item.notes && <div className="sm:col-span-2"><dt className="text-xs text-slate-500">Notas</dt><dd className="mt-1 whitespace-pre-wrap">{item.notes}</dd></div>}</dl>
      <div className="flex flex-wrap gap-2">{canEdit && <><button className="secondary-button" onClick={() => onEdit("edit")}>Editar</button><button className="secondary-button" onClick={() => onEdit("reschedule")}>Reprogramar</button></>}{actions.includes("confirm") && <button className="primary-button" onClick={() => action.mutate({ name: "confirm" })}>Confirmar</button>}{actions.includes("start") && <button className="primary-button" onClick={() => action.mutate({ name: "start" })}>Iniciar</button>}{actions.includes("complete") && <button className="primary-button" onClick={() => action.mutate({ name: "complete" })}>Completar</button>}{actions.includes("cancel") && user && hasPermission(user.permissions, "appointments.cancel") && <button className="secondary-button text-red-600" onClick={() => setReasonAction("cancel")}>Cancelar turno</button>}{actions.includes("no-show") && <button className="secondary-button" onClick={() => setReasonAction("no-show")}>Marcar ausente</button>}{validPhone && <button className="secondary-button text-emerald-700" onClick={whatsapp}><MessageCircle size={17} />WhatsApp</button>}</div>
      <div><h4 className="text-sm font-semibold">Historial de estados</h4><div className="mt-3 space-y-2">{item.statusEvents.map((event) => <div key={event.id} className="flex gap-3 text-sm"><Clock3 className="mt-0.5 shrink-0 text-slate-400" size={16} /><p><span className="font-medium">{statusLabels[event.toStatus]}</span>{event.reason ? ` · ${event.reason}` : ""}<span className="block text-xs text-slate-400">{new Intl.DateTimeFormat("es-AR", { timeZone: zone, dateStyle: "short", timeStyle: "short" }).format(new Date(event.createdAt))} · {event.user.firstName} {event.user.lastName}</span></p></div>)}</div></div></div></Modal>
    {reasonAction && <AppointmentReasonModal action={reasonAction} reason={reason} pending={action.isPending} onReason={setReason} onClose={() => setReasonAction(null)} onConfirm={() => action.mutate({ name: reasonAction, reason })} />}
  </>;
}

export function AppointmentReasonModal({ action, reason, pending, onReason, onClose, onConfirm }: { action: "cancel" | "no-show"; reason: string; pending: boolean; onReason: (value: string) => void; onClose: () => void; onConfirm: () => void }) { return <Modal title={action === "cancel" ? "Cancelar turno" : "Marcar ausencia"} onClose={onClose} width="max-w-md"><Field label="Motivo"><textarea autoFocus className="field min-h-24" value={reason} onChange={(event) => onReason(event.target.value)} /></Field><div className="mt-5 flex justify-end gap-3"><button className="secondary-button" onClick={onClose}>Volver</button><button className="primary-button" disabled={pending || (action === "cancel" && reason.trim().length < 2)} onClick={onConfirm}>Confirmar</button></div></Modal>; }

export function AgendaEmptyState({ onCreate }: { onCreate: () => void }) { return <div className="p-10 text-center"><CalendarClock className="mx-auto text-slate-300" size={42} /><p className="mt-4 font-medium">Todavía no hay turnos.</p><button className="primary-button mt-4" onClick={onCreate}><UserRound size={17} />Crear turno</button></div>; }
