import { useQuery } from "@tanstack/react-query";
import { ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useAuth } from "../hooks/useAuth";
import { apiRequest } from "../services/api/client";
import type { AuditLogRow, AuditOptions, ReportPage } from "../types/api";

const todayIn = (zone: string) => new Intl.DateTimeFormat("en-CA", { timeZone: zone, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const shift = (date: string, days: number) => { const value = new Date(`${date}T12:00:00Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10); };
const friendly: Record<string, string> = { PAYMENT_CREATED: "Cobro registrado", PAYMENT_AMOUNT_ADJUSTED: "Importe de cobro ajustado", APPOINTMENT_CREATED: "Turno creado", APPOINTMENT_UPDATED: "Turno actualizado", APPOINTMENT_RESCHEDULED: "Turno reprogramado", CASH_OPENED: "Caja abierta", CASH_CLOSED: "Caja cerrada", CASH_MOVEMENT_CREATED: "Movimiento de caja registrado" };

export function AuditPage() {
  const { user } = useAuth(); const today = todayIn(user!.business.timezone);
  const [from, setFrom] = useState(shift(today, -29)); const [to, setTo] = useState(today); const [userId, setUserId] = useState(""); const [action, setAction] = useState(""); const [entity, setEntity] = useState(""); const [page, setPage] = useState(1);
  const options = useQuery({ queryKey: ["audit", "options"], queryFn: () => apiRequest<AuditOptions>("/audit/options") });
  const params = new URLSearchParams({ from, to, page: String(page), pageSize: "20", ...(userId ? { userId } : {}), ...(action ? { action } : {}), ...(entity ? { entity } : {}) });
  const logs = useQuery({ queryKey: ["audit", params.toString()], queryFn: () => apiRequest<ReportPage<AuditLogRow>>(`/audit?${params}`), staleTime: 10_000 });
  if (!user) return null;
  const dateTime = new Intl.DateTimeFormat(user.business.locale, { timeZone: user.business.timezone, dateStyle: "short", timeStyle: "medium" });
  return <div className="space-y-6"><header><p className="text-sm font-medium brand-text">Seguridad y trazabilidad</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Auditoría</h1><p className="mt-2 text-slate-500">Eventos sensibles del negocio, con usuario, fecha y contexto saneado.</p></header>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Field label="Desde"><input className="field" type="date" value={from} max={to} onChange={(e) => { setFrom(e.target.value); setPage(1); }} /></Field><Field label="Hasta"><input className="field" type="date" value={to} min={from} onChange={(e) => { setTo(e.target.value); setPage(1); }} /></Field><Field label="Usuario"><select className="field" value={userId} onChange={(e) => { setUserId(e.target.value); setPage(1); }}><option value="">Todos</option>{options.data?.users.map((item) => <option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</select></Field><Field label="Acción"><select className="field" value={action} onChange={(e) => { setAction(e.target.value); setPage(1); }}><option value="">Todas</option>{options.data?.actions.map((item) => <option key={item}>{friendly[item] ?? item}</option>)}</select></Field><Field label="Entidad"><select className="field" value={entity} onChange={(e) => { setEntity(e.target.value); setPage(1); }}><option value="">Todas</option>{options.data?.entities.map((item) => <option key={item}>{item}</option>)}</select></Field></div></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-5"><ShieldCheck className="text-slate-400" size={20} /><div><h2 className="font-semibold">Registro de eventos</h2><p className="text-sm text-slate-500">{logs.data ? `${logs.data.meta.total} eventos · ${logs.data.timezone}` : "Consultando trazabilidad"}</p></div></div>{logs.isLoading ? <div className="m-5 h-64 animate-pulse rounded-xl bg-slate-100" /> : logs.isError ? <div className="p-10 text-center"><p>No pudimos cargar la auditoría.</p><button className="secondary-button mt-4" onClick={() => void logs.refetch()}>Reintentar</button></div> : logs.data?.items.length ? <div className="divide-y divide-slate-100">{logs.data.items.map((item) => <article key={item.id} className="grid gap-3 p-5 lg:grid-cols-[12rem_1fr_12rem] lg:items-start"><div><p className="text-sm font-medium">{dateTime.format(new Date(item.createdAt))}</p><p className="mt-1 text-xs text-slate-500">{item.ipAddress ?? "IP no registrada"}</p></div><div><p className="font-medium">{friendly[item.action] ?? item.action}</p><p className="mt-1 text-sm text-slate-500">{item.entity}{item.entityId ? ` · ${item.entityId}` : ""}</p>{item.metadata !== null && <details className="mt-3"><summary className="cursor-pointer text-xs font-medium brand-text">Ver contexto protegido</summary><pre className="mt-2 max-w-full overflow-auto rounded-lg bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(item.metadata, null, 2)}</pre></details>}</div><div className="text-sm lg:text-right"><p className="font-medium">{item.user ? `${item.user.firstName} ${item.user.lastName}` : "Sistema"}</p><p className="text-xs text-slate-500">{item.user?.username ?? "Sin usuario"}</p></div></article>)}</div> : <div className="p-12 text-center text-sm text-slate-500">No hay eventos para estos filtros.</div>}{logs.data && <footer className="flex items-center justify-between border-t border-slate-100 p-4 text-sm"><span>Página {logs.data.meta.page} de {logs.data.meta.totalPages}</span><div className="flex gap-2"><button className="secondary-button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Anterior</button><button className="secondary-button" disabled={page >= logs.data.meta.totalPages} onClick={() => setPage((value) => value + 1)}>Siguiente</button></div></footer>}</section>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-xs font-medium text-slate-600">{label}</span>{children}</label>; }
