import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Mail, Phone, Plus, Search, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ClientFormModal } from "../components/ClientFormModal";
import { apiRequest } from "../services/api/client";
import type { Client, ClientPage } from "../types/api";
import { clientsPath } from "../utils/client-form";

const message = (error: unknown) => error instanceof Error ? error.message : "No se pudo cargar el listado.";
type Status = "all" | "active" | "inactive";

export function ClientsPage() {
  const navigate = useNavigate(); const [search, setSearch] = useState(""); const [debounced, setDebounced] = useState(""); const [status, setStatus] = useState<Status>("all"); const [page, setPage] = useState(1); const [creating, setCreating] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { setDebounced(search); setPage(1); }, 350); return () => window.clearTimeout(timer); }, [search]);
  const query = useQuery({ queryKey: ["clients", page, debounced, status], queryFn: () => apiRequest<ClientPage>(clientsPath(page, 20, debounced, status)) });
  const changeStatus = (next: Status) => { setStatus(next); setPage(1); };
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="brand-text text-sm font-medium">Relaciones</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Clientes</h1><p className="mt-2 text-slate-500">Información de contacto y ficha comercial de cada persona.</p></div><button className="primary-button w-full sm:w-auto" onClick={() => setCreating(true)}><Plus size={18} />Nuevo cliente</button></header>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><label className="relative w-full sm:max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={17} /><input className="field pl-10" aria-label="Buscar clientes" placeholder="Nombre, teléfono o email…" value={search} onChange={(event) => setSearch(event.target.value)} /></label><div className="grid grid-cols-3 rounded-xl bg-slate-100 p-1" aria-label="Estado de clientes">{(["all", "active", "inactive"] as const).map((value) => <button key={value} className={`rounded-lg px-3 py-2 text-sm font-medium ${status === value ? "bg-white text-slate-900 shadow-sm" : "text-slate-500"}`} onClick={() => changeStatus(value)}>{value === "all" ? "Todos" : value === "active" ? "Activos" : "Inactivos"}</button>)}</div></div>
      {query.isLoading ? <div className="space-y-3 p-5" aria-label="Cargando clientes">{[1,2,3,4].map((index) => <div key={index} className="h-20 animate-pulse rounded-xl bg-slate-100" />)}</div> : query.isError ? <div className="p-10 text-center"><p className="font-medium">No pudimos cargar los clientes.</p><p className="mt-2 text-sm text-slate-500">{message(query.error)}</p><button className="secondary-button mt-4" onClick={() => void query.refetch()}>Reintentar</button></div> : <ClientCollection clients={query.data?.items ?? []} searching={Boolean(debounced) || status !== "all"} onAdd={() => setCreating(true)} onOpen={(id) => navigate(`/clients/${id}`)} />}
      {query.data && query.data.meta.total > 0 && <footer className="flex flex-col gap-3 border-t border-slate-100 px-4 py-4 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>{query.data.meta.total} {query.data.meta.total === 1 ? "cliente" : "clientes"}</p><div className="flex items-center justify-between gap-3"><button className="secondary-button px-3" aria-label="Página anterior" disabled={page <= 1 || query.isFetching} onClick={() => setPage((value) => value - 1)}><ChevronLeft size={17} /></button><span>Página {query.data.meta.page} de {query.data.meta.totalPages}</span><button className="secondary-button px-3" aria-label="Página siguiente" disabled={page >= query.data.meta.totalPages || query.isFetching} onClick={() => setPage((value) => value + 1)}><ChevronRight size={17} /></button></div></footer>}
    </section>
    {creating && <ClientFormModal onClose={() => setCreating(false)} onSaved={async (saved) => { await query.refetch(); navigate(`/clients/${saved.id}`); }} onViewDuplicate={(id) => navigate(`/clients/${id}`)} />}
  </div>;
}

export function ClientCollection({ clients, searching, onAdd, onOpen }: { clients: Client[]; searching: boolean; onAdd: () => void; onOpen: (id: string) => void }) {
  if (!clients.length) return <div className="px-5 py-14 text-center"><UserRound className="mx-auto text-slate-300" size={40} /><p className="mt-4 font-medium text-slate-700">{searching ? "No encontramos clientes con esos criterios." : "Tu negocio todavía no tiene clientes registrados."}</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{searching ? "Probá con otro nombre, teléfono, email o estado." : "Creá la primera ficha para empezar a construir tu base de clientes."}</p>{!searching && <button className="primary-button mt-5" onClick={onAdd}>Agregar primer cliente</button>}</div>;
  return <div className="divide-y divide-slate-100">{clients.map((client) => <article key={client.id} className="flex flex-col gap-4 p-5 transition hover:bg-slate-50 sm:flex-row sm:items-center sm:justify-between"><button className="min-w-0 text-left" onClick={() => onOpen(client.id)}><span className="flex flex-wrap items-center gap-2"><span className="font-semibold text-slate-900">{client.fullName}</span><span className={`rounded-full px-2 py-0.5 text-xs font-medium ${client.active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{client.active ? "Activo" : "Inactivo"}</span></span><span className="mt-2 flex flex-col gap-1 text-sm text-slate-500 sm:flex-row sm:gap-4">{client.phone && <span className="flex items-center gap-1.5"><Phone size={14} />{client.phone}</span>}{client.email && <span className="flex min-w-0 items-center gap-1.5 break-all"><Mail className="shrink-0" size={14} />{client.email}</span>}{!client.phone && !client.email && <span>Sin datos de contacto</span>}</span></button><button className="secondary-button w-full shrink-0 sm:w-auto" onClick={() => onOpen(client.id)}>Ver ficha</button></article>)}</div>;
}
