import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import { AuthContext } from "../features/auth/auth-context";
import { apiRequest } from "../services/api/client";
import type { Appointment, AuthUser, CashRegister } from "../types/api";
import { formatMoney } from "../utils/money";
import { ChargeAppointmentModal } from "./AgendaPage";
import { CashActionModal, CashDashboard, CashEmptyState } from "./CashPage";

vi.mock("../services/api/client", () => ({ apiRequest: vi.fn(), ApiClientError: class ApiClientError extends Error { constructor(message: string, public status: number, public code?: string) { super(message); } } }));
afterEach(() => { cleanup(); vi.clearAllMocks(); });

const user = (permissions: string[]): AuthUser => ({ id: "u", businessId: "b", username: "admin", email: "a@test", firstName: "Admin", lastName: "Test", role: { id: "r", code: "ADMIN", name: "Admin" }, permissions, business: { id: "b", name: "BorKin", locale: "es-AR", currency: "ARS", timezone: "America/Argentina/Cordoba", primaryColor: "#2563EB" } });
function Providers({ children, permissions = ["cash.view", "cash.open", "cash.close", "cash.movements", "payments.charge", "payments.adjust_amount"] }: { children: React.ReactNode; permissions?: string[] }) { return <MemoryRouter><QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><AuthContext.Provider value={{ user: user(permissions), loading: false, login: vi.fn(), logout: vi.fn(), refreshUser: vi.fn() }}>{children}</AuthContext.Provider></QueryClientProvider></MemoryRouter>; }
const totals = { paymentCount: 2, totalPayments: "12000.00", totalSales: "12000.00", cashSales: "5000.00", nonCashSales: "7000.00", manualIncome: "2000.00", expenses: "1000.00", withdrawals: "3000.00", expectedCash: "13000.00", byMethod: [{ id: "pm", paymentMethodId: "pm", name: "Efectivo", kind: "CASH" as const, amount: "5000.00", count: 1 }] };
const register: CashRegister = { id: "c", status: "ABIERTA", openedAt: "2026-08-11T12:00:00Z", closedAt: null, openingAmount: "10000.00", openingNotes: null, expectedCash: null, countedCash: null, difference: null, closingNotes: null, openedBy: { id: "u", firstName: "Admin", lastName: "Test" }, closedBy: null, totals, recentMovements: [] };
const turn: Appointment = { id: "a", clientId: "c", serviceId: "s", employeeId: "e", startAt: "2026-08-11T12:00:00Z", endAt: "2026-08-11T12:30:00Z", durationMinutes: 30, serviceName: "Corte", price: "10000.00", status: "EN_CURSO", notes: null, version: 1, client: { id: "c", firstName: "Cliente", lastName: "Test", phone: null, phoneNormalized: null, whatsapp: null, active: true }, service: { id: "s", name: "Corte", color: "#000000", active: true }, employee: { id: "e", firstName: "Pro", lastName: "Uno", color: "#000000", photoUrl: null, active: true }, statusEvents: [], payments: [] };

describe("Caja Fase 5", () => {
  it("formatea importes grandes y negativos sin convertir centavos a Number", () => { expect(formatMoney("999999999999.99", "ARS", "es-AR")).toContain("999.999.999.999,99"); expect(formatMoney("-0.01", "ARS", "es-AR")).toMatch(/-.*0,01/); });
  it("muestra estado sin caja y permite iniciar apertura", () => { const open = vi.fn(); render(<CashEmptyState canOpen onOpen={open} />); expect(screen.getByText("No hay una caja abierta.")).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: "Abrir caja" })); expect(open).toHaveBeenCalledOnce(); });
  it("dashboard usa totales backend y expone movimientos/cierre", () => { const action = vi.fn(); render(<CashDashboard register={register} money={(value) => `$${value}`} canMove canClose onAction={action} />); expect(screen.getByText("$13000.00")).toBeTruthy(); expect(screen.getByText("$12000.00")).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: "Ingreso" })); fireEvent.click(screen.getByRole("button", { name: "Cerrar caja" })); expect(action).toHaveBeenNthCalledWith(1, "income"); expect(action).toHaveBeenNthCalledWith(2, "close"); });
  it("cierre exige motivo si contado difiere del esperado", () => { render(<Providers><CashActionModal action="close" register={register} money={(value) => `$${value}`} onClose={vi.fn()} onSaved={vi.fn()} /></Providers>); const confirm = screen.getByRole("button", { name: "Confirmar" }) as HTMLButtonElement; expect(confirm.disabled).toBe(false); fireEvent.change(screen.getByRole("textbox", { name: "Efectivo contado" }), { target: { value: "12500" } }); expect(screen.getByText("$-500.00")).toBeTruthy(); expect(confirm.disabled).toBe(true); fireEvent.change(screen.getByRole("textbox", { name: "Motivo" }), { target: { value: "Faltante" } }); expect(confirm.disabled).toBe(false); });
});

describe("Cobro de turno", () => {
  it("sin caja bloquea el cobro y ofrece ir a Caja", async () => { vi.mocked(apiRequest).mockImplementation(async (path) => path === "/payment-methods/options" ? [{ id: "pm", name: "Efectivo", kind: "CASH" }] : null); render(<Providers><ChargeAppointmentModal item={turn} onClose={vi.fn()} onCharged={vi.fn()} /></Providers>); expect(await screen.findByText("Debés abrir una caja antes de registrar cobros.")).toBeTruthy(); expect(screen.getByRole("link", { name: "Ir a Caja" })).toBeTruthy(); expect((screen.getByRole("button", { name: "Confirmar cobro" }) as HTMLButtonElement).disabled).toBe(true); });
  it("sin permiso mantiene monto readonly", async () => { vi.mocked(apiRequest).mockImplementation(async (path) => path === "/payment-methods/options" ? [{ id: "pm", name: "Efectivo", kind: "CASH" }] : register); render(<Providers permissions={["payments.charge"]}><ChargeAppointmentModal item={turn} onClose={vi.fn()} onCharged={vi.fn()} /></Providers>); await screen.findByText(/Caja abierta/); expect((screen.getByRole("textbox", { name: "Monto a cobrar" }) as HTMLInputElement).readOnly).toBe(true); });
  it("deshabilita doble click y completa tras una única request", async () => { let resolveCharge!: (value: Appointment) => void; const pending = new Promise<Appointment>((resolve) => { resolveCharge = resolve; }); vi.mocked(apiRequest).mockImplementation((path) => { if (path === "/payment-methods/options") return Promise.resolve([{ id: "pm", name: "Efectivo", kind: "CASH" }]); if (path === "/cash/current") return Promise.resolve(register); return pending; }); const charged = vi.fn(); render(<Providers><ChargeAppointmentModal item={turn} onClose={vi.fn()} onCharged={charged} /></Providers>); await screen.findByText(/Caja abierta/); fireEvent.change(screen.getByRole("combobox", { name: "Método de pago" }), { target: { value: "pm" } }); const button = screen.getByRole("button", { name: "Confirmar cobro" }); fireEvent.click(button); fireEvent.click(button); await waitFor(() => expect((button as HTMLButtonElement).disabled).toBe(true)); expect(vi.mocked(apiRequest).mock.calls.filter(([path]) => String(path).endsWith("/charge"))).toHaveLength(1); resolveCharge({ ...turn, status: "COMPLETADO" }); await waitFor(() => expect(charged).toHaveBeenCalledOnce()); });
});
