import { useQuery } from "@tanstack/react-query";
import { Download, FileSpreadsheet } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useAuth } from "../hooks/useAuth";
import { apiDownload, apiRequest } from "../services/api/client";
import type { AnalyticsOptions, AppointmentReportRow, ClientReportRow, MovementReportRow, ReportPage, SalesReportRow, ServiceReportRow } from "../types/api";

const tabs = [{ id: "sales", label: "Ventas" }, { id: "appointments", label: "Turnos" }, { id: "movements", label: "Movimientos" }, { id: "clients", label: "Clientes" }, { id: "services", label: "Servicios" }] as const;
type ReportKind = typeof tabs[number]["id"];
type Row = SalesReportRow | AppointmentReportRow | MovementReportRow | ClientReportRow | ServiceReportRow;
const todayIn = (zone: string) => new Intl.DateTimeFormat("en-CA", { timeZone: zone, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());

export function ReportsPage() {
  const { user } = useAuth();
  const today = todayIn(user!.business.timezone);
  const [kind, setKind] = useState<ReportKind>("sales"); const [from, setFrom] = useState(`${today.slice(0, 8)}01`); const [to, setTo] = useState(today); const [employeeId, setEmployeeId] = useState(""); const [serviceId, setServiceId] = useState(""); const [paymentMethodId, setPaymentMethodId] = useState(""); const [status, setStatus] = useState(""); const [type, setType] = useState(""); const [page, setPage] = useState(1); const [exporting, setExporting] = useState(false);
  const options = useQuery({ queryKey: ["analytics", "options"], queryFn: () => apiRequest<AnalyticsOptions>("/analytics/options") });
  const params = new URLSearchParams({ from, to, page: String(page), pageSize: "20", ...(employeeId ? { employeeId } : {}), ...(serviceId ? { serviceId } : {}), ...(paymentMethodId ? { paymentMethodId } : {}), ...(status ? { status } : {}), ...(type ? { type } : {}) });
  const report = useQuery({ queryKey: ["reports", kind, params.toString()], queryFn: () => apiRequest<ReportPage<Row>>(`/reports/${kind}?${params}`), staleTime: 15_000 });
  if (!user) return null;
  const money = new Intl.NumberFormat(user.business.locale, { style: "currency", currency: user.business.currency });
  const dateTime = new Intl.DateTimeFormat(user.business.locale, { timeZone: user.business.timezone, dateStyle: "short", timeStyle: "short" });
  const changeKind = (value: ReportKind) => { setKind(value); setPage(1); setStatus(""); setType(""); };
  async function exportCsv() { setExporting(true); try { const exportParams = new URLSearchParams(params); exportParams.delete("page"); exportParams.delete("pageSize"); const result = await apiDownload(`/reports/${kind}/export?${exportParams}`); const url = URL.createObjectURL(result.blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = result.filename; document.body.append(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url); toast.success("Reporte CSV descargado."); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo exportar."); } finally { setExporting(false); } }
  return <div className="space-y-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium brand-text">Datos exportables</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Reportes</h1><p className="mt-2 text-slate-500">Listados paginados y exportaciones con los filtros aplicados.</p></div><button className="primary-button" disabled={exporting || report.isLoading} onClick={() => void exportCsv()}><Download size={18} />{exporting ? "Exportando…" : "Exportar CSV"}</button></header>
    <div className="overflow-x-auto"><div className="inline-flex min-w-full gap-1 rounded-xl border border-slate-200 bg-white p-1 sm:min-w-0">{tabs.map((tab) => <button key={tab.id} className={`min-h-10 flex-1 rounded-lg px-4 text-sm font-medium ${kind === tab.id ? "nav-active" : "text-slate-600 hover:bg-slate-50"}`} onClick={() => changeKind(tab.id)}>{tab.label}</button>)}</div></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Field label="Desde"><input className="field" type="date" value={from} max={to} onChange={(e) => { setFrom(e.target.value); setPage(1); }} /></Field><Field label="Hasta"><input className="field" type="date" value={to} min={from} onChange={(e) => { setTo(e.target.value); setPage(1); }} /></Field>{kind !== "clients" && <Field label="Profesional"><select className="field" value={employeeId} onChange={(e) => { setEmployeeId(e.target.value); setPage(1); }}><option value="">Todos</option>{options.data?.employees.map((item) => <option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</select></Field>}{["sales","appointments","services"].includes(kind) && <Field label="Servicio"><select className="field" value={serviceId} onChange={(e) => { setServiceId(e.target.value); setPage(1); }}><option value="">Todos</option>{options.data?.services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>}{["sales","movements"].includes(kind) && <Field label="Método de pago"><select className="field" value={paymentMethodId} onChange={(e) => { setPaymentMethodId(e.target.value); setPage(1); }}><option value="">Todos</option>{options.data?.paymentMethods.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>}{kind === "appointments" && <Field label="Estado"><select className="field" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">Todos</option>{["PENDIENTE","CONFIRMADO","EN_CURSO","COMPLETADO","CANCELADO","AUSENTE"].map((item) => <option key={item}>{item.replaceAll("_", " ")}</option>)}</select></Field>}{kind === "movements" && <Field label="Tipo"><select className="field" value={type} onChange={(e) => { setType(e.target.value); setPage(1); }}><option value="">Todos</option>{["VENTA","INGRESO_MANUAL","EGRESO","RETIRO"].map((item) => <option key={item}>{item.replaceAll("_", " ")}</option>)}</select></Field>}</div></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-5"><FileSpreadsheet className="text-slate-400" size={20} /><div><h2 className="font-semibold">{tabs.find((item) => item.id === kind)?.label}</h2><p className="text-sm text-slate-500">{report.data ? `${report.data.meta.total} resultados · zona ${report.data.timezone}` : "Consultando datos"}</p></div></div>{report.isLoading ? <div className="m-5 h-64 animate-pulse rounded-xl bg-slate-100" /> : report.isError ? <div className="p-10 text-center"><p>No pudimos cargar el reporte.</p><button className="secondary-button mt-4" onClick={() => void report.refetch()}>Reintentar</button></div> : report.data?.items.length ? <ReportRows kind={kind} rows={report.data.items} money={money} dateTime={dateTime} /> : <div className="p-12 text-center text-sm text-slate-500">No hay resultados para estos filtros.</div>}
      {report.data && <footer className="flex items-center justify-between border-t border-slate-100 p-4 text-sm"><span>Página {report.data.meta.page} de {report.data.meta.totalPages}</span><div className="flex gap-2"><button className="secondary-button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Anterior</button><button className="secondary-button" disabled={page >= report.data.meta.totalPages} onClick={() => setPage((value) => value + 1)}>Siguiente</button></div></footer>}
    </section>
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-xs font-medium text-slate-600">{label}</span>{children}</label>; }
function ReportRows({ kind, rows, money, dateTime }: { kind: ReportKind; rows: Row[]; money: Intl.NumberFormat; dateTime: Intl.DateTimeFormat }) { const values = rows.map((row) => columns(kind, row, money, dateTime)); const headers = headersFor(kind); return <><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{headers.map((header) => <th key={header} className="px-5 py-3 font-medium">{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{values.map((cells,index) => <tr key={rows[index]!.id} className="hover:bg-slate-50">{cells.map((cell,cellIndex) => <td key={`${headers[cellIndex]}-${cell}`} className="px-5 py-4">{cell}</td>)}</tr>)}</tbody></table></div><div className="divide-y divide-slate-100 md:hidden">{values.map((cells,index) => <article key={rows[index]!.id} className="space-y-2 p-4">{cells.map((cell,cellIndex) => <div key={headers[cellIndex]} className="flex justify-between gap-4 text-sm"><span className="text-slate-500">{headers[cellIndex]}</span><span className="text-right font-medium">{cell}</span></div>)}</article>)}</div></>; }
function headersFor(kind: ReportKind) { if (kind === "sales") return ["Fecha","Cliente","Servicio","Profesional","Método","Precio original","Monto cobrado","Usuario"]; if (kind === "appointments") return ["Fecha","Cliente","Servicio","Profesional","Estado","Precio histórico","Monto cobrado"]; if (kind === "movements") return ["Fecha","Tipo","Concepto","Método","Monto","Usuario","Caja abierta"]; if (kind === "clients") return ["Alta","Cliente","Contacto","Turnos","Última visita","Estado"]; return ["Servicio","Cobros","Ventas","Ticket promedio"]; }
function columns(kind: ReportKind, row: Row, money: Intl.NumberFormat, dateTime: Intl.DateTimeFormat) { if (kind === "sales") { const item = row as SalesReportRow; return [dateTime.format(new Date(item.createdAt)), item.clientName, item.appointment.serviceName, item.employeeName, item.paymentMethod.name, money.format(Number(item.originalPrice)), money.format(Number(item.amount)), item.recordedByName]; } if (kind === "appointments") { const item = row as AppointmentReportRow; return [dateTime.format(new Date(item.startAt)), item.clientName, item.serviceName, item.employeeName, item.status.replaceAll("_", " "), money.format(Number(item.price)), item.paidAmount === null ? "—" : money.format(Number(item.paidAmount))]; } if (kind === "movements") { const item = row as MovementReportRow; return [dateTime.format(new Date(item.occurredAt)), item.type.replaceAll("_", " "), item.concept, item.paymentMethod?.name ?? "—", money.format(Number(item.amount)), item.createdByName, dateTime.format(new Date(item.cashRegister.openedAt))]; } if (kind === "clients") { const item = row as ClientReportRow; return [dateTime.format(new Date(item.createdAt)), item.clientName, item.phone ?? item.email ?? "—", String(item.appointmentCount), item.lastVisit ? dateTime.format(new Date(item.lastVisit)) : "—", item.active ? "Activo" : "Inactivo"]; } const item = row as ServiceReportRow; return [item.name, String(item.count), money.format(Number(item.amount)), money.format(Number(item.average))]; }
