import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Layers3, Pencil, Plus, Search, Scissors } from "lucide-react";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";
import { Field, Modal } from "../components/Modal";
import { useAuth } from "../hooks/useAuth";
import { apiRequest } from "../services/api/client";
import type { Category, Service } from "../types/api";
import { formatMoney } from "../utils/money";
import { serviceFormSchema, type ServiceValues } from "../utils/service-form";

const categorySchema = z.object({ name: z.string().trim().min(2, "Ingresá al menos 2 caracteres."), description: z.string() });
type CategoryValues = z.infer<typeof categorySchema>;
const message = (error: unknown) => error instanceof Error ? error.message : "No se pudo completar la operación.";

export function ServicesPage() {
  const { user } = useAuth();
  const client = useQueryClient(); const [tab, setTab] = useState<"services" | "categories">("services"); const [search, setSearch] = useState(""); const [debounced, setDebounced] = useState(""); const [serviceModal, setServiceModal] = useState<Service | "new" | null>(null); const [categoryModal, setCategoryModal] = useState<Category | "new" | null>(null); const [confirm, setConfirm] = useState<{ kind: "service" | "category"; item: Service | Category } | null>(null);
  useEffect(() => { const timer = window.setTimeout(() => setDebounced(search), 300); return () => window.clearTimeout(timer); }, [search]);
  const services = useQuery({ queryKey: ["services", debounced], queryFn: () => apiRequest<Service[]>(`/services?pageSize=100&search=${encodeURIComponent(debounced)}`) });
  const categories = useQuery({ queryKey: ["categories", debounced], queryFn: () => apiRequest<Category[]>(`/service-categories?pageSize=100&search=${encodeURIComponent(debounced)}`) });
  const categoryOptions = useQuery({ queryKey: ["category-options"], queryFn: () => apiRequest<Array<{ id: string; name: string }>>("/service-categories/options") });
  const invalidate = async () => { await Promise.all([client.invalidateQueries({ queryKey: ["services"] }), client.invalidateQueries({ queryKey: ["categories"] }), client.invalidateQueries({ queryKey: ["category-options"] }), client.invalidateQueries({ queryKey: ["service-options"] })]); };
  const status = useMutation({ mutationFn: ({ kind, item }: NonNullable<typeof confirm>) => apiRequest(kind === "service" ? `/services/${item.id}` : `/service-categories/${item.id}`, { method: "PATCH", body: JSON.stringify({ active: !item.active }) }), onSuccess: async () => { toast.success("Estado actualizado."); setConfirm(null); await invalidate(); }, onError: (error) => toast.error(message(error)) });
  const loading = tab === "services" ? services.isLoading : categories.isLoading; const error = tab === "services" ? services.error : categories.error; const data = tab === "services" ? services.data : categories.data;
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="brand-text text-sm font-medium">Catálogo</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Servicios</h1><p className="mt-2 text-slate-500">Definí la oferta, duración y precios del negocio.</p></div><button className="primary-button" onClick={() => tab === "services" ? setServiceModal("new") : setCategoryModal("new")}><Plus size={18} />{tab === "services" ? "Nuevo servicio" : "Nueva categoría"}</button></header>
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex rounded-xl bg-slate-100 p-1" role="tablist" aria-label="Secciones del catálogo"><button role="tab" aria-selected={tab === "services"} className={`rounded-lg px-4 py-2 text-sm font-medium ${tab === "services" ? "bg-white shadow-sm" : "text-slate-500"}`} onClick={() => setTab("services")}>Servicios</button><button role="tab" aria-selected={tab === "categories"} className={`rounded-lg px-4 py-2 text-sm font-medium ${tab === "categories" ? "bg-white shadow-sm" : "text-slate-500"}`} onClick={() => setTab("categories")}>Categorías</button></div><label className="relative w-full sm:w-72"><Search className="absolute left-3 top-3 text-slate-400" size={17} /><input className="field pl-10" aria-label="Buscar en el catálogo" placeholder="Buscar…" value={search} onChange={(event) => setSearch(event.target.value)} /></label></div>
      {loading ? <div className="space-y-3 p-5">{[1,2,3].map((i) => <div key={i} className="h-20 animate-pulse rounded-xl bg-slate-100" />)}</div> : error ? <State title="No pudimos cargar el catálogo" text={message(error)} /> : !data?.length ? <State icon={tab === "services" ? <Scissors /> : <Layers3 />} title={tab === "services" ? "Todavía no hay servicios cargados." : "Todavía no hay categorías cargadas."} action={<button className="primary-button mt-4" onClick={() => tab === "services" ? setServiceModal("new") : setCategoryModal("new")}>Crear primero</button>} /> : tab === "services" ? <div className="divide-y divide-slate-100">{services.data?.map((item) => <article key={item.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 gap-3"><span className="mt-1 h-10 w-2 shrink-0 rounded-full" style={{ backgroundColor: item.color }} /><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-medium">{item.name}</h2><Badge active={item.active} /></div><p className="mt-1 text-sm text-slate-500">{item.category?.name ?? "Sin categoría"} · {item.durationMinutes} min · {formatMoney(item.price, user?.business.currency, user?.business.locale)}</p>{item.description && <p className="mt-1 text-sm text-slate-400">{item.description}</p>}</div></div><div className="flex gap-2"><button className="secondary-button" onClick={() => setServiceModal(item)}><Pencil size={16} />Editar</button><button className="secondary-button" onClick={() => setConfirm({ kind: "service", item })}>{item.active ? "Desactivar" : "Activar"}</button></div></article>)}</div> : <div className="divide-y divide-slate-100">{categories.data?.map((item) => <article key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="font-medium">{item.name}</h2><Badge active={item.active} /></div><p className="mt-1 text-sm text-slate-500">{item.description || "Sin descripción"}</p></div><div className="flex gap-2"><button className="secondary-button" onClick={() => setCategoryModal(item)}><Pencil size={16} />Editar</button><button className="secondary-button" onClick={() => setConfirm({ kind: "category", item })}>{item.active ? "Desactivar" : "Activar"}</button></div></article>)}</div>}
    </section>
    {serviceModal && <ServiceForm item={serviceModal} categories={categoryOptions.data ?? []} close={() => setServiceModal(null)} saved={invalidate} />}
    {categoryModal && <CategoryForm item={categoryModal} close={() => setCategoryModal(null)} saved={invalidate} />}
    {confirm && <Modal title={`¿${confirm.item.active ? "Desactivar" : "Activar"} ${confirm.kind === "service" ? "servicio" : "categoría"}?`} onClose={() => setConfirm(null)}><p className="text-sm leading-6 text-slate-500">La información histórica se conservará. Si se desactiva, dejará de estar disponible para operaciones futuras.</p><div className="mt-6 flex justify-end gap-3"><button className="secondary-button" onClick={() => setConfirm(null)}>Cancelar</button><button className="primary-button" disabled={status.isPending} onClick={() => status.mutate(confirm)}>{status.isPending ? "Guardando…" : "Confirmar"}</button></div></Modal>}
  </div>;
}

function ServiceForm({ item, categories, close, saved }: { item: Service | "new"; categories: Array<{ id: string; name: string }>; close: () => void; saved: () => Promise<void> }) {
  const editing = item !== "new"; const form = useForm<ServiceValues>({ resolver: zodResolver(serviceFormSchema), defaultValues: editing ? { name: item.name, categoryId: item.category?.id ?? "", description: item.description ?? "", price: item.price, durationMinutes: item.durationMinutes, color: item.color } : { name: "", categoryId: "", description: "", price: "0.00", durationMinutes: 30, color: "#2563EB" } });
  const mutation = useMutation({ mutationFn: (values: ServiceValues) => apiRequest<Service>(editing ? `/services/${item.id}` : "/services", { method: editing ? "PATCH" : "POST", body: JSON.stringify({ ...values, categoryId: values.categoryId || null, description: values.description || null, price: values.price.replace(",", ".") }) }), onSuccess: async () => { toast.success(editing ? "Servicio actualizado." : "Servicio creado."); await saved(); close(); }, onError: (error) => toast.error(message(error)) });
  return <Modal title={editing ? "Editar servicio" : "Nuevo servicio"} onClose={close}><form className="grid gap-4 sm:grid-cols-2" onSubmit={form.handleSubmit((values) => mutation.mutate(values))}><Field label="Nombre" error={form.formState.errors.name?.message}><input className="field" {...form.register("name")} /></Field><Field label="Categoría"><select className="field" {...form.register("categoryId")}><option value="">Sin categoría</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Field label="Precio" error={form.formState.errors.price?.message}><input className="field" inputMode="decimal" {...form.register("price")} /></Field><Field label="Duración (minutos)" error={form.formState.errors.durationMinutes?.message}><input className="field" type="number" {...form.register("durationMinutes", { valueAsNumber: true })} /></Field><Field label="Color" error={form.formState.errors.color?.message}><input className="h-11 w-full rounded-xl border border-slate-300 p-1" type="color" {...form.register("color")} /></Field><Field label="Descripción"><textarea className="field min-h-24" {...form.register("description")} /></Field><div className="flex justify-end gap-3 border-t border-slate-100 pt-4 sm:col-span-2"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={mutation.isPending}>{mutation.isPending ? "Guardando…" : "Guardar"}</button></div></form></Modal>;
}

function CategoryForm({ item, close, saved }: { item: Category | "new"; close: () => void; saved: () => Promise<void> }) {
  const editing = item !== "new"; const form = useForm<CategoryValues>({ resolver: zodResolver(categorySchema), defaultValues: editing ? { name: item.name, description: item.description ?? "" } : { name: "", description: "" } });
  const mutation = useMutation({ mutationFn: (values: CategoryValues) => apiRequest<Category>(editing ? `/service-categories/${item.id}` : "/service-categories", { method: editing ? "PATCH" : "POST", body: JSON.stringify({ ...values, description: values.description || null }) }), onSuccess: async () => { toast.success(editing ? "Categoría actualizada." : "Categoría creada."); await saved(); close(); }, onError: (error) => toast.error(message(error)) });
  return <Modal title={editing ? "Editar categoría" : "Nueva categoría"} onClose={close}><form className="space-y-4" onSubmit={form.handleSubmit((values) => mutation.mutate(values))}><Field label="Nombre" error={form.formState.errors.name?.message}><input className="field" {...form.register("name")} /></Field><Field label="Descripción"><textarea className="field min-h-24" {...form.register("description")} /></Field><div className="flex justify-end gap-3 border-t border-slate-100 pt-4"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={mutation.isPending}>{mutation.isPending ? "Guardando…" : "Guardar"}</button></div></form></Modal>;
}

function Badge({ active }: { active: boolean }) { return <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{active ? "Activo" : "Inactivo"}</span>; }
function State({ icon, title, text, action }: { icon?: React.ReactNode; title: string; text?: string; action?: React.ReactNode }) { return <div className="p-10 text-center text-slate-500">{icon && <div className="mx-auto mb-3 w-fit">{icon}</div>}<p className="font-medium text-slate-700">{title}</p>{text && <p className="mt-2 text-sm">{text}</p>}{action}</div>; }
