import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, ImageUp, Trash2 } from "lucide-react";
import { useEffect, useRef } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";
import { Field } from "../components/Modal";
import { useAuth } from "../hooks/useAuth";
import { apiRequest, assetUrl } from "../services/api/client";
import type { BusinessSettings } from "../types/api";

const schema = z.object({ name: z.string().trim().min(2, "Ingresá al menos 2 caracteres."), phone: z.string(), whatsapp: z.string(), email: z.union([z.literal(""), z.email("Email inválido.")]), address: z.string(), instagram: z.string(), currency: z.string().regex(/^[A-Z]{3}$/, "Usá 3 letras mayúsculas."), locale: z.string().min(2), timezone: z.string().min(3), primaryColor: z.string().regex(/^#[0-9A-Fa-f]{6}$/, "Color hexadecimal inválido.") });
type Values = z.infer<typeof schema>;
const empty = { name: "", phone: "", whatsapp: "", email: "", address: "", instagram: "", currency: "ARS", locale: "es-AR", timezone: "America/Argentina/Cordoba", primaryColor: "#2563EB" };
const message = (error: unknown) => error instanceof Error ? error.message : "No se pudo completar la operación.";

export function SettingsPage() {
  const queryClient = useQueryClient(); const inputRef = useRef<HTMLInputElement>(null); const { refreshUser } = useAuth();
  const query = useQuery({ queryKey: ["business-settings"], queryFn: () => apiRequest<BusinessSettings>("/settings/business") });
  const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: empty });
  useEffect(() => { if (query.data) form.reset({ name: query.data.name, phone: query.data.phone ?? "", whatsapp: query.data.whatsapp ?? "", email: query.data.email ?? "", address: query.data.address ?? "", instagram: query.data.instagram ?? "", currency: query.data.currency, locale: query.data.locale, timezone: query.data.timezone, primaryColor: query.data.primaryColor }); }, [query.data, form]);
  const refresh = async () => { await queryClient.invalidateQueries({ queryKey: ["business-settings"] }); await refreshUser(); };
  const save = useMutation({ mutationFn: (values: Values) => apiRequest<BusinessSettings>("/settings/business", { method: "PATCH", body: JSON.stringify(Object.fromEntries(Object.entries(values).map(([key, value]) => [key, value === "" && key !== "name" ? null : value]))) }), onSuccess: async () => { toast.success("Configuración guardada."); await refresh(); }, onError: (error) => toast.error(message(error)) });
  const logo = useMutation({ mutationFn: async (file: File) => { const data = new FormData(); data.append("logo", file); return apiRequest<BusinessSettings>("/settings/business/logo", { method: "PUT", body: data }); }, onSuccess: async () => { toast.success("Logo actualizado."); await refresh(); }, onError: (error) => toast.error(message(error)) });
  const removeLogo = useMutation({ mutationFn: () => apiRequest<BusinessSettings>("/settings/business/logo", { method: "DELETE" }), onSuccess: async () => { toast.success("Logo eliminado."); await refresh(); }, onError: (error) => toast.error(message(error)) });
  if (query.isLoading) return <div className="h-72 animate-pulse rounded-2xl bg-slate-100" />;
  if (query.isError) return <ErrorState text={message(query.error)} retry={() => void query.refetch()} />;
  return <div className="space-y-6"><header><p className="brand-text text-sm font-medium">Configuración</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Datos del negocio</h1><p className="mt-2 text-slate-500">Identidad, contacto y preferencias regionales de tu operación.</p></header>
    <section className="grid gap-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:grid-cols-[240px_1fr] lg:p-7"><div><div className="grid aspect-square place-items-center overflow-hidden rounded-2xl border border-dashed border-slate-300 bg-slate-50">{query.data?.logoUrl ? <img className="h-full w-full object-contain p-3" src={assetUrl(query.data.logoUrl) ?? ""} alt="Logo del negocio" /> : <Building2 className="text-slate-300" size={52} />}</div><input ref={inputRef} className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const selected = event.target.files?.[0]; if (selected) logo.mutate(selected); event.target.value = ""; }} /><div className="mt-3 grid gap-2"><button className="secondary-button" disabled={logo.isPending} onClick={() => inputRef.current?.click()}><ImageUp size={17} />{logo.isPending ? "Subiendo…" : "Cambiar logo"}</button>{query.data?.logoUrl && <button className="secondary-button text-red-600" disabled={removeLogo.isPending} onClick={() => removeLogo.mutate()}><Trash2 size={17} />Eliminar</button>}</div><p className="mt-3 text-xs leading-5 text-slate-500">PNG, JPEG o WebP. Máximo 2 MB.</p></div>
      <form className="grid gap-4 sm:grid-cols-2" onSubmit={form.handleSubmit((values) => save.mutate(values))}><Field label="Nombre del negocio" error={form.formState.errors.name?.message}><input className="field" {...form.register("name")} /></Field><Field label="Email" error={form.formState.errors.email?.message}><input className="field" type="email" {...form.register("email")} /></Field><Field label="Teléfono"><input className="field" {...form.register("phone")} /></Field><Field label="WhatsApp"><input className="field" {...form.register("whatsapp")} /></Field><Field label="Dirección"><input className="field" {...form.register("address")} /></Field><Field label="Instagram"><input className="field" {...form.register("instagram")} /></Field><Field label="Moneda" error={form.formState.errors.currency?.message}><input className="field uppercase" maxLength={3} {...form.register("currency")} /></Field><Field label="Locale" error={form.formState.errors.locale?.message}><input className="field" {...form.register("locale")} /></Field><Field label="Zona horaria" error={form.formState.errors.timezone?.message}><input className="field" {...form.register("timezone")} /></Field><Field label="Color principal" error={form.formState.errors.primaryColor?.message}><div className="flex gap-2"><input className="h-11 w-14 rounded-xl border border-slate-300 p-1" type="color" {...form.register("primaryColor")} /><input className="field uppercase" {...form.register("primaryColor")} /></div></Field><div className="flex justify-end border-t border-slate-100 pt-5 sm:col-span-2"><button className="primary-button w-full sm:w-auto" disabled={save.isPending}>{save.isPending ? "Guardando…" : "Guardar cambios"}</button></div></form></section></div>;
}

function ErrorState({ text, retry }: { text: string; retry: () => void }) { return <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center"><p className="font-medium">No pudimos cargar la configuración.</p><p className="mt-2 text-sm text-slate-500">{text}</p><button className="secondary-button mt-4" onClick={retry}>Reintentar</button></div>; }
