import { useQuery } from "@tanstack/react-query";
import { ArrowDownRight, ArrowUpRight, BarChart3, CalendarRange, Minus, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";
import { useAuth } from "../hooks/useAuth";
import { apiRequest } from "../services/api/client";
import type { AnalyticsOptions, AnalyticsOverview, AnalyticsRankings, AnalyticsTimeseries } from "../types/api";

type Range = { from: string; to: string };
const shiftDate = (date: string, days: number) => { const value = new Date(`${date}T12:00:00Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10); };
const todayIn = (zone: string) => new Intl.DateTimeFormat("en-CA", { timeZone: zone, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());

export function StatisticsPage() {
  const { user } = useAuth();
  const today = todayIn(user!.business.timezone);
  const [range, setRange] = useState<Range>({ from: shiftDate(today, -29), to: today });
  const [employeeId, setEmployeeId] = useState("");
  const params = new URLSearchParams({ from: range.from, to: range.to, ...(employeeId ? { employeeId } : {}) }).toString();
  const options = useQuery({ queryKey: ["analytics", "options"], queryFn: () => apiRequest<AnalyticsOptions>("/analytics/options") });
  const overview = useQuery({ queryKey: ["analytics", "overview", params], queryFn: () => apiRequest<AnalyticsOverview>(`/analytics/overview?${params}`) });
  const timeseries = useQuery({ queryKey: ["analytics", "timeseries", params], queryFn: () => apiRequest<AnalyticsTimeseries>(`/analytics/timeseries?${params}`) });
  const rankings = useQuery({ queryKey: ["analytics", "rankings", params], queryFn: () => apiRequest<AnalyticsRankings>(`/analytics/rankings?${params}`) });
  if (!user) return null;
  const money = new Intl.NumberFormat(user.business.locale, { style: "currency", currency: user.business.currency, maximumFractionDigits: 0 });
  const compact = new Intl.NumberFormat(user.business.locale, { notation: "compact", maximumFractionDigits: 1 });
  const loading = overview.isLoading || timeseries.isLoading || rankings.isLoading;
  const error = overview.isError || timeseries.isError || rankings.isError;
  const setPreset = (kind: "today" | "week" | "month" | "30") => setRange(kind === "today" ? { from: today, to: today } : kind === "week" ? { from: shiftDate(today, -6), to: today } : kind === "month" ? { from: `${today.slice(0, 8)}01`, to: today } : { from: shiftDate(today, -29), to: today });
  return <div className="space-y-6">
    <header><p className="text-sm font-medium brand-text">Análisis del negocio</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Estadísticas</h1><p className="mt-2 text-slate-500">Ventas cobradas y actividad operativa, comparadas con el período anterior equivalente.</p></header>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-wrap gap-2">{([['today','Hoy'],['week','7 días'],['month','Este mes'],['30','30 días']] as const).map(([key,label]) => <button key={key} className="secondary-button" onClick={() => setPreset(key)}>{label}</button>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Field label="Desde"><input className="field" type="date" value={range.from} max={range.to} onChange={(e) => setRange((value) => ({ ...value, from: e.target.value }))} /></Field><Field label="Hasta"><input className="field" type="date" value={range.to} min={range.from} onChange={(e) => setRange((value) => ({ ...value, to: e.target.value }))} /></Field><Field label="Profesional"><select className="field" value={employeeId} onChange={(e) => setEmployeeId(e.target.value)}><option value="">Todos los profesionales</option>{options.data?.employees.map((item) => <option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</select></Field></div></section>
    {loading ? <Loading /> : error ? <ErrorState retry={() => { void overview.refetch(); void timeseries.refetch(); void rankings.refetch(); }} /> : overview.data && timeseries.data && rankings.data && <>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Ventas cobradas" value={money.format(Number(overview.data.current.sales))} comparison={overview.data.comparison.sales} /><Metric label="Turnos" value={String(overview.data.current.appointmentCount)} comparison={overview.data.comparison.appointments} detail={`${overview.data.current.completedCount} completados`} /><Metric label="Clientes atendidos" value={String(overview.data.current.clientCount)} comparison={overview.data.comparison.clients} detail={`${overview.data.current.newClientCount} altas nuevas`} /><Metric label="Ticket promedio" value={money.format(Number(overview.data.current.averageTicket))} detail={`${overview.data.current.paymentCount} cobros`} /></section>
      <section className="grid gap-6 xl:grid-cols-2"><ChartCard title="Ventas por día" subtitle="Sólo pagos registrados"><LineChart points={timeseries.data.points.map((item) => Number(item.sales))} labels={timeseries.data.points.map((item) => item.date.slice(5))} format={(value) => compact.format(value)} /></ChartCard><ChartCard title="Turnos por día" subtitle="Todos los estados operativos"><LineChart points={timeseries.data.points.map((item) => item.appointments)} labels={timeseries.data.points.map((item) => item.date.slice(5))} format={String} color="#0f766e" /></ChartCard></section>
      <section className="grid gap-6 xl:grid-cols-3"><RankCard title="Servicios con más ventas" items={rankings.data.services} money={money} /><RankCard title="Ventas por profesional" items={rankings.data.employees} money={money} /><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Métodos de pago</h2><p className="mt-1 text-sm text-slate-500">Participación sobre cobros registrados</p><div className="mt-5 space-y-4">{rankings.data.paymentMethods.length ? rankings.data.paymentMethods.map((item) => <div key={item.id}><div className="mb-1.5 flex justify-between gap-3 text-sm"><span className="font-medium">{item.name}</span><span>{item.percentage}% · {money.format(Number(item.sales))}</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full brand-bg" style={{ width: `${Math.min(100, Number(item.percentage))}%` }} /></div></div>) : <Empty />}</div></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-600 shadow-sm"><div className="flex gap-3"><CalendarRange className="shrink-0 text-slate-400" size={20} /><p>Período actual: <strong>{overview.data.period.from}</strong> a <strong>{overview.data.period.to}</strong>. Comparación: {overview.data.period.previousFrom} a {overview.data.period.previousTo}. Cancelación: <strong>{overview.data.current.cancellationRate}%</strong>; ausencias: <strong>{overview.data.current.absentCount}</strong>. Zona horaria: {overview.data.period.timezone}.</p></div></section>
    </>}
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-xs font-medium text-slate-600">{label}</span>{children}</label>; }
function Metric({ label, value, comparison, detail }: { label: string; value: string; comparison?: string | null; detail?: string }) { const number = comparison === null || comparison === undefined ? null : Number(comparison); const Icon = number === null || number === 0 ? Minus : number > 0 ? ArrowUpRight : ArrowDownRight; return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><div className="mt-3 flex items-center gap-1.5 text-xs"><Icon size={15} className={number === null || number === 0 ? "text-slate-400" : number > 0 ? "text-emerald-600" : "text-red-600"} /><span>{number === null ? "Sin base comparable" : `${number > 0 ? "+" : ""}${number.toFixed(1)}% vs. período anterior`}</span></div>{detail && <p className="mt-2 text-xs text-slate-500">{detail}</p>}</article>; }
function ChartCard({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><TrendingUp className="text-slate-400" size={20} /><div><h2 className="font-semibold">{title}</h2><p className="text-sm text-slate-500">{subtitle}</p></div></div><div className="mt-5">{children}</div></div>; }
function LineChart({ points, labels, format, color = "#2563eb" }: { points: number[]; labels: string[]; format: (value: number) => string; color?: string }) { const { line, area, max } = useMemo(() => { const maximum = Math.max(...points, 1); const coords = points.map((value, index) => `${points.length === 1 ? 50 : (index / (points.length - 1)) * 100},${92 - (value / maximum) * 78}`); return { line: coords.join(" "), area: `0,100 ${coords.join(" ")} 100,100`, max: maximum }; }, [points]); if (!points.length) return <Empty />; return <div><svg className="h-56 w-full overflow-visible" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={`Gráfico, máximo ${format(max)}`}><polygon points={area} fill={color} opacity=".08" /><polyline points={line} fill="none" stroke={color} strokeWidth="2" vectorEffect="non-scaling-stroke" />{points.map((value,index) => <circle key={`${labels[index]}-${value}`} cx={points.length === 1 ? 50 : (index/(points.length-1))*100} cy={92-(value/max)*78} r="1.2" fill={color}><title>{labels[index]}: {format(value)}</title></circle>)}</svg><div className="mt-2 flex justify-between text-[10px] text-slate-400"><span>{labels[0]}</span><span>{labels[Math.floor(labels.length / 2)]}</span><span>{labels.at(-1)}</span></div></div>; }
function RankCard({ title, items, money }: { title: string; items: Array<{ id: string; name: string; sales: string; count: number }>; money: Intl.NumberFormat }) { const max = Math.max(...items.map((item) => Number(item.sales)), 1); return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><BarChart3 className="text-slate-400" size={20} /><h2 className="font-semibold">{title}</h2></div><div className="mt-5 space-y-4">{items.length ? items.map((item,index) => <div key={item.id}><div className="mb-1.5 flex justify-between gap-3 text-sm"><span className="truncate"><strong className="mr-2 text-slate-400">{index + 1}</strong>{item.name}</span><span className="shrink-0">{money.format(Number(item.sales))}</span></div><div className="h-1.5 rounded-full bg-slate-100"><div className="h-1.5 rounded-full bg-slate-700" style={{ width: `${(Number(item.sales)/max)*100}%` }} /></div><p className="mt-1 text-right text-[11px] text-slate-400">{item.count} cobros</p></div>) : <Empty />}</div></div>; }
function Empty() { return <p className="py-8 text-center text-sm text-slate-500">Sin datos para el período.</p>; }
function Loading() { return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Cargando estadísticas">{[1,2,3,4,5,6,7,8].map((item) => <div key={item} className="h-36 animate-pulse rounded-2xl bg-slate-100" />)}</div>; }
function ErrorState({ retry }: { retry: () => void }) { return <div className="rounded-2xl border border-red-200 bg-white p-10 text-center"><p>No pudimos cargar las estadísticas.</p><button className="secondary-button mt-4" onClick={retry}>Reintentar</button></div>; }
